/*
 * Sentech Camera Driver for Linux
 *
 * Copyright (C) 2017 Omron Sentech CO.,LTD
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 */

#ifndef __STCAM_DD_CAM_DEF_H__
#define __STCAM_DD_CAM_DEF_H__

enum stcam_e_fpga2_sub_category
{
	e_fpga2_sub_fps_by_v_blanking = 0,
	e_fpga2_sub_exposure_mode,
	e_fpga2_sub_trigger_software,
	e_fpga2_sub_frame_start_trigger_mode,
	e_fpga2_sub_frame_start_trigger_source,
	e_fpga2_sub_frame_start_trigger_delay,
	e_fpga2_sub_frame_start_trigger_overlap,
	e_fpga2_sub_frame_burst_trigger_mode,
	e_fpga2_sub_frame_burst_trigger_source,
	e_fpga2_sub_frame_burst_trigger_delay,
	e_fpga2_sub_frame_burst_trigger_overlap,
	e_fpga2_sub_exposure_start_trigger_mode,
	e_fpga2_sub_exposure_start_trigger_source,
	e_fpga2_sub_exposure_start_trigger_delay,
	e_fpga2_sub_exposure_start_trigger_overlap,
	e_fpga2_sub_exposure_end_trigger_mode,
	e_fpga2_sub_exposure_end_trigger_source,
	e_fpga2_sub_exposure_end_trigger_delay,
	e_fpga2_sub_exposure_end_trigger_overlap,
	e_fpga2_sub_analog_offset,
	e_fpga2_sub_line_debounce_time,
	e_fpga2_sub_sensor_shutter_mode,
	e_fpga2_sub_digital_gain_enabled,
	e_fpga2_sub_io_reset_switch_enabled,
	e_fpga2_sub_fps_decimal,
	e_fpga2_sub_frame_rate_base,
	e_fpga2_sub_max_v_blanking_for_fps,
	e_fpga2_sub_camera_temperature,
	e_fpga2_sub_exposure_time_base,
	e_fpga2_sub_max_analog_black_level,
	e_fpga2_sub_max_digital_gain,
	e_fpga2_sub_min_digital_gain,
	e_fpga2_sub_exposure_time_offset,
	e_fpga2_sub_camera_feature_1,
	e_fpga2_sub_camera_feature_3,
	e_fpga2_sub_camera_feature_5,
	e_fpga2_sub_camera_feature_9,
	e_fpga2_sub_camera_feature_a,
	e_fpga2_sub_camera_feature_c,
	e_fpga2_sub_hdr_control_size,
	e_fpga2_sub_hdr_control_parametor_0,
	e_fpga2_sub_hdr_control_parametor_1,
	e_fpga2_sub_category_max
};

#define VENDOR_ID		0x1421

#define STC_MB33USB		0x0110
#define STC_MC33USB		0x0210
#define STC_MB83USB		0x0310
#define STC_MC83USB		0x0410
#define STC_MB133USB	0x0510
#define STC_MC133USB	0x0610
#define STC_MB152USB	0x0710
#define STC_MC152USB	0x0810
#define STC_MB202USB	0x0910
#define STC_MC202USB	0x1010
#define STC_MBA5MUSB3	0x0111
#define STC_MCA5MUSB3	0x0211
#define STC_MBE132U3V	0x0112
#define STC_MCE132U3V	0x0212
#define STC_MBCM401U3V	0x0113
#define STC_MCCM401U3V	0x0213
#define STC_MBCM200U3V	0x0313
#define STC_MCCM200U3V	0x0413
#define STC_MBS241U3V	0x0713
#define STC_MCS241U3V	0x0813
#define STC_MBS510U3V	0x0315
#define STC_MCS510U3V	0x0415
#define STC_MBS322U3V	0x0515
#define STC_MCS322U3V	0x0615
#define STC_MBS891U3V	0x0116
#define STC_MCS891U3V	0x0216
#define STC_MBS123BU3V	0x0316
#define STC_MCS123BU3V	0x0416
#define STC_MBS43U3V	0x0516
#define STC_MCS43U3V	0x0616
#define STC_MBS163U3V	0x0716
#define STC_MCS163U3V	0x0816

#define STC_COM_REQ_TYPE_OUT	0x40
#define STC_COM_REQ_TYPE_IN		0xC0

#define STC_COM_REQ_CAMERA_INFO			0x11
#define STC_COM_REQ_PICTURE_SIZE		0x12
#define STC_COM_REQ_PIXEL_BYTE			0x13
#define STC_COM_REQ_MEMORY_RESET		0x20
#define STC_COM_REQ_SHUTTER_GAIN		0x21
#define STC_COM_REQ_CLOCK				0x22
#define STC_COM_REQ_SOFTWARE_TRIGER		0x30
#define STC_COM_REQ_FPGA				0x80
#define STC_COM_REQ_FX3					0x81
#define STC_COM_REQ_FPGA2				0x82
#define STC_COM_REQ_EEPROM_W			0xF9
#define STC_COM_REQ_EEPROM_INFO			0xFA

#define STC_COM_LEN_CAMERA_INFO		0x40
#define STC_COM_LEN_PICTURE_SIZE	0x40
#define STC_COM_LEN_PIXEL_BYTE		0x06
#define STC_COM_LEN_SHUTTER_GAIN	0x40
#define STC_COM_LEN_CLOCK			0x0A
#define STC_COM_LEN_FPGA			0xE2
#define STC_COM_LEN_FPGA2			0x04 * e_fpga2_sub_category_max

#define STC_COM_ADR_CAMERA_INFO_VID						2
#define STC_COM_ADR_CAMERA_INFO_PID						4
#define STC_COM_ADR_CAMERA_INFO_FPGA_VERSION			6
#define STC_COM_ADR_CAMERA_INFO_FIRM_VERSION			8
#define STC_COM_ADR_CAMERA_INFO_COLOR_ARRAY				10
#define STC_COM_ADR_CAMERA_INFO_HEADER_SIZE				12
#define STC_COM_ADR_CAMERA_INFO_ENABLE_IMAGE_SIZE_MODE	14
#define STC_COM_ADR_CAMERA_INFO_ENABLE_TRANSFER_BPP		18
#define STC_COM_ADR_CAMERA_INFO_CAMERA_RAM_SIZE			22
#define STC_COM_ADR_CAMERA_INFO_ENABLE_SCAN_MODE		26
#define STC_COM_ADR_CAMERA_INFO_MOST_FIRST_CLOCK		28
#define STC_COM_ADR_CAMERA_INFO_MOST_SLOW_CLOCK			32
#define STC_COM_ADR_CAMERA_INFO_STANDARD_CLOCK			36
#define STC_COM_ADR_CAMERA_INFO_ENABLE_CLOCK_MODE		40
#define STC_COM_ADR_CAMERA_INFO_ENABLE_SHUTTER_MODE		44
#define STC_COM_ADR_CAMERA_INFO_ENABLE_GAIN_MODE		46
#define STC_COM_ADR_CAMERA_INFO_ENABLE_WB_MODE			48
#define STC_COM_ADR_CAMERA_INFO_ENABLE_TRG_MODE			52
#define STC_COM_ADR_CAMERA_INFO_MAXIMUM_IMAGE_WIDTH		56
#define STC_COM_ADR_CAMERA_INFO_MAXIMUM_IMAGE_HEIGHT	60

#define STC_COM_ADR_PICTURE_SIZE_LENGTH								0
#define STC_COM_ADR_PICTURE_SIZE_REQUEST							1
#define STC_COM_ADR_PICTURE_SIZE_IMAGE_SIZE_MODE					2
#define STC_COM_ADR_PICTURE_SIZE_WIDTH								6
#define STC_COM_ADR_PICTURE_SIZE_HEIGHT								10
#define STC_COM_ADR_PICTURE_SIZE_OFFSET_X							14
#define STC_COM_ADR_PICTURE_SIZE_OFFSET_Y							18
#define STC_COM_ADR_PICTURE_SIZE_SCAN_MODE							22
#define STC_COM_ADR_PICTURE_SIZE_TOTAL_LEN							24
#define STC_COM_ADR_PICTURE_SIZE_TOTAL_V_LINE						26
#define STC_COM_ADR_PICTURE_SIZE_TOTAL_H_CLOCK						28
#define STC_COM_ADR_PICTURE_SIZE_MAX_GAIN							30
#define STC_COM_ADR_PICTURE_SIZE_DEFAULT_GAIN						32
#define STC_COM_ADR_PICTURE_SIZE_DEFAULT_DIGITAL_GAIN				34
#define STC_COM_ADR_PICTURE_SIZE_EXP_FINE_ADJUSTMENT_MAX_VALUE		36
#define STC_COM_ADR_PICTURE_SIZE_MAX_SHORT_EXP_FINE_ADJUSTMENT		40
#define STC_COM_ADR_PICTURE_SIZE_MAX_SHORT_EXP_COARSE_ADJUSTMENT	44
#define STC_COM_ADR_PICTURE_SIZE_MAX_LONG_EXP_FINE_ADJUSTMENT		48
#define STC_COM_ADR_PICTURE_SIZE_MAX_LONG_EXP_COARSE_ADJUSTMENT		52
#define STC_COM_ADR_PICTURE_SIZE_MAX_ROI_COUNT						56
#define STC_COM_ADR_PICTURE_SIZE_REGION_MODE						60
#define STC_COM_ADR_PICTURE_SIZE_ROI_WIDTH							64
#define STC_COM_ADR_PICTURE_SIZE_ROI_HEIGHT							68
#define STC_COM_ADR_PICTURE_SIZE_ROI_OFFSET_X						72
#define STC_COM_ADR_PICTURE_SIZE_ROI_OFFSET_Y						76

#define STC_COM_ADR_PIXEL_BYTE_TRANSFER_BITS_PER_PIXEL		2

#define STC_COM_ADR_SHUTTER_GAIN_EXP_LINE_L		2
#define STC_COM_ADR_SHUTTER_GAIN_EXP_CLOCK_L	4
#define STC_COM_ADR_SHUTTER_GAIN_GAIN			6
#define STC_COM_ADR_SHUTTER_GAIN_EXP_LINE_H		10

#define STC_COM_ADR_CLOCK_MODE		2
#define STC_COM_ADR_CLOCK_SPEED		6

#define STC_COM_ADR_FPGA_IO_PIN_DIRECTION				0x00
#define STC_COM_ADR_FPGA_IO_PIN_POLARITY				0x01
#define STC_COM_ADR_FPGA_IO_PIN_STATUS					0x02
#define STC_COM_ADR_FPGA_IO_PIN_MODE_0					0x04
#define STC_COM_ADR_FPGA_IO_PIN_MODE_1					0x05
#define STC_COM_ADR_FPGA_IO_PIN_MODE_2					0x06
#define STC_COM_ADR_FPGA_IO_PIN_MODE_3					0x07
#define STC_COM_ADR_FPGA_RESET_SW_ENABLED				0x0E
#define STC_COM_ADR_FPGA_LED							0x0F
#define STC_COM_ADR_FPGA_CDS_OFFSET						0x13
#define STC_COM_ADR_FPGA_DIGITAL_GAIN					0x14
#define STC_COM_ADR_FPGA_DIGITAL_CLAMP					0x15
#define STC_COM_ADR_FPGA_V_BLNAK_FOR_FPS				0x17
#define STC_COM_ADR_FPGA_BINNING_DECIMATION				0x21
#define STC_COM_ADR_FPGA_BINNING_SUM					0x2E
#define STC_COM_ADR_FPGA_TRIGGER_MODE_L					0x30
#define STC_COM_ADR_FPGA_TRIGGER_MODE_H					0x31
#define STC_COM_ADR_FPGA_EXPOSURE_DELAY_L				0x32
#define STC_COM_ADR_FPGA_EXPOSURE_DELAY_H				0x33
#define STC_COM_ADR_FPGA_STROBO_DELAY_L					0x34
#define STC_COM_ADR_FPGA_STROBO_DELAY_H					0x35
#define STC_COM_ADR_FPGA_STROBO_END_DELAY_L				0x36
#define STC_COM_ADR_FPGA_STROBO_END_DELAY_H				0x37
#define STC_COM_ADR_FPGA_TRIGGER_DELAY_L				0x38
#define STC_COM_ADR_FPGA_TRIGGER_DELAY_H				0x39
#define STC_COM_ADR_FPGA_TRIGGER_PULSE_WIDTH_L			0x3A
#define STC_COM_ADR_FPGA_TRIGGER_PULSE_WIDTH_H			0x3B
#define STC_COM_ADR_FPGA_READOUT_DELAY					0x3C
#define STC_COM_ADR_FPGA_MIRROR_MODE					0x3F
#define STC_COM_ADR_FPGA_WB_GAIN_R						0x40
#define STC_COM_ADR_FPGA_WB_GAIN_GR						0x41
#define STC_COM_ADR_FPGA_WB_GAIN_GB						0x42
#define STC_COM_ADR_FPGA_WB_GAIN_B						0x43
#define STC_COM_ADR_FPGA_WB_MODE						0x44
#define STC_COM_ADR_FPGA_AE_MAX_EXP_L					0x45
#define STC_COM_ADR_FPGA_AE_MAX_EXP_H					0x46
#define STC_COM_ADR_FPGA_AE_MIN_EXP_L					0x47
#define STC_COM_ADR_FPGA_AE_MIN_EXP_H					0x48
#define STC_COM_ADR_FPGA_ALC_MODE						0x49
#define STC_COM_ADR_FPGA_ALC_TARGET_LEVEL				0x4A
#define STC_COM_ADR_FPGA_AGC_MAX_GAIN					0x4B
#define STC_COM_ADR_FPGA_AGC_MIN_GAIN					0x4C
#define STC_COM_ADR_FPGA_GAMMA							0x4D
#define STC_COM_ADR_FPGA_DEFFECT_PIXEL_CORRECTION_MODE	0x4E
#define STC_COM_ADR_FPGA_REFRESH_RC_RO					0x50
#define STC_COM_ADR_FPGA_FPS_DECIMAL					0x56
#define STC_COM_ADR_FPGA_FPS_INTEGER					0x57
#define STC_COM_ADR_FPGA_CUR_EXP_TIME_L					0x58
#define STC_COM_ADR_FPGA_CUR_EXP_TIME_H					0x59
#define STC_COM_ADR_FPGA_AE_MAX_EXP_TIME_L				0x5A
#define STC_COM_ADR_FPGA_AE_MAX_EXP_TIME_H				0x5B
#define STC_COM_ADR_FPGA_AE_MIN_EXP_TIME_L				0x5C
#define STC_COM_ADR_FPGA_AE_MIN_EXP_TIME_H				0x5D
#define STC_COM_ADR_FPGA_SENTECH_U3V_MODE				0x65
#define STC_COM_ADR_FPGA_SW_STATUS						0x66
#define STC_COM_ADR_FPGA_CAMERA_FUNCTION0				0x68
#define STC_COM_ADR_FPGA_CAMERA_FUNCTION1				0x69
#define STC_COM_ADR_FPGA_CAMERA_FUNCTION2				0x6A
#define STC_COM_ADR_FPGA_CAMERA_FUNCTION3				0x6B
#define STC_COM_ADR_FPGA_CAMERA_FUNCTION4				0x6C
#define STC_COM_ADR_FPGA_CAMERA_FUNCTION5				0x6D
#define STC_COM_ADR_FPGA_CAMERA_FUNCTION6				0x6E
#define STC_COM_ADR_FPGA_CAMERA_FUNCTION7				0x6F
#define STC_COM_ADR_FPGA_CAMERA_FUNCTION8				0x70

#define STC_COM_ADR_EEPROM_W_INDEX						0x0151
#define STC_COM_ADR_EEPROM_W_CAMERA_ID_START			0x6F00
#define STC_COM_ADR_EEPROM_W_CAMERA_LENGTH_START		0x6F05
#define STC_COM_ADR_EEPROM_W_CAMERA_NAME_START			0x6F06
#define STC_COM_ADR_EEPROM_W_USER_DATA_START			0x7000
#define STC_COM_ADR_EEPROM_INFO_CAMERA_ID_START			0x0100
#define STC_COM_ADR_EEPROM_INFO_CAMERA_LENGTH_START		0x0105
#define STC_COM_ADR_EEPROM_INFO_CAMERA_NAME_START		0x0106
#define STC_COM_ADR_EEPROM_INFO_USER_DATA_START			0x0200

#define STC_COM_VAL_FPGA_READ				0x0080
#define STC_COM_VAL_FPGA_WRITE				0x8000
#define STC_COM_VAL_FPGA_WRITE_NO_REFRESH	0x0000

#define STC_COM_FPGA2_CATEGORY_OFFSET_ACQUISITION_CONTROL			0x000C
#define STC_COM_FPGA2_CATEGORY_OFFSET_ANALOG_CONTROL				0x0010
#define STC_COM_FPGA2_CATEGORY_OFFSET_DIGITAL_IO_CONTROL			0x0014
#define STC_COM_FPGA2_CATEGORY_OFFSET_VENDOR_UNIQUE_CONTROL			0x0048
#define STC_COM_FPGA2_CATEGORY_OFFSET_USB_CAMERA_ORG_FUNCTION		0x0050
#define STC_COM_FPGA2_CATEGORY_OFFSET_USB_CAMERA_STATUS				0x0058
#define STC_COM_FPGA2_CATEGORY_OFFSET_USB_CAMERA_FEATURE			0x005C
#define STC_COM_FPGA2_CATEGORY_OFFSET_HDR_CONTROL					0x0070

#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_FPS_BY_V_BLANKING				0x0010
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_EXPOSURE_MODE					0x0018
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_TRIGGER_SOFTWARE				0x0028
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_FRAME_START_TRIGGER_MODE		0x002C
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_FRAME_START_TRIGGER_SOURCE		0x0030
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_FRAME_START_TRIGGER_DELAY		0x0034
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_FRAME_START_TRIGGER_OVERLAP	0x003C
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_FRAME_BURST_TRIGGER_MODE		0x0040
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_FRAME_BURST_TRIGGER_SOURCE		0x0044
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_FRAME_BURST_TRIGGER_DELAY		0x0048
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_FRAME_BURST_TRIGGER_OVERLAP	0x0050
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_EXPOSURE_START_TRIGGER_MODE	0x0058
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_EXPOSURE_START_TRIGGER_SOURCE	0x005C
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_EXPOSURE_START_TRIGGER_DELAY	0x0060
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_EXPOSURE_START_TRIGGER_OVERLAP	0x0068
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_EXPOSURE_END_TRIGGER_MODE		0x006C
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_EXPOSURE_END_TRIGGER_SOURCE	0x0070
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_EXPOSURE_END_TRIGGER_DELAY		0x0074
#define STC_COM_FPGA2_SUB_OFFSET_ACQUISITION_CONTROL_EXPOSURE_END_TRIGGER_OVERLAP	0x007C
#define STC_COM_FPGA2_SUB_OFFSET_ANALOG_CONTROL_ANALOG_OFFSET						0x0008
#define STC_COM_FPGA2_SUB_OFFSET_DIGITAL_IO_CONTROL_LINE_DEBOUNCE_TIME				0x0030
#define STC_COM_FPGA2_SUB_OFFSET_VENDOR_UNIQUE_CONTROL_SENSOR_SHUTTER_MODE			0x0004
#define STC_COM_FPGA2_SUB_OFFSET_VENDOR_UNIQUE_CONTROL_DIGITAL_GAIN_ENABLED			0x000C
#define STC_COM_FPGA2_SUB_OFFSET_USB_ORIGINAL_FUNCTION_SAVE_IO_RESET_SWITCH_ENABLED	0x0018
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_STATUS_FPS_DECIMAL						0x0014
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_STATUS_FRAME_RATE_BASE					0x0054
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_STATUS_MAX_V_BLANKING_FOR_FPS			0x0058
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_STATUS_CAMERA_TEMPERATURE				0x005C
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_STATUS_EXPOSURE_TIME_BASE				0x0060
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_STATUS_MAX_ANALOG_BLACK_LEVEL			0x0070
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_STATUS_MAX_DIGITAL_GAIN					0x0084
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_STATUS_MIN_DIGITAL_GAIN					0x0088
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_STATUS_EXPOSURE_TIME_OFFSET				0x00AC
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_FEATURE_CAMERA_FEATURE_1				0x0008
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_FEATURE_CAMERA_FEATURE_3				0x0010
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_FEATURE_CAMERA_FEATURE_5				0x0018
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_FEATURE_CAMERA_FEATURE_9				0x0028
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_FEATURE_CAMERA_FEATURE_A				0x002C
#define STC_COM_FPGA2_SUB_OFFSET_USB_CAMERA_FEATURE_CAMERA_FEATURE_C				0x0034
#define STC_COM_FPGA2_SUB_OFFSET_HDR_CONTROL_SIZE									0x0000
#define STC_COM_FPGA2_SUB_OFFSET_HDR_CONTROL_PARAMETOR_0							0x0004
#define STC_COM_FPGA2_SUB_OFFSET_HDR_CONTROL_PARAMETOR_1							0x0008

#define STC_COM_BIT_FPGA_FUNCTION0_VGA90FPS									0
#define STC_COM_BIT_FPGA_FUNCTION0_STARTSTOP								1
#define STC_COM_BIT_FPGA_FUNCTION0_MEMORY									2
#define STC_COM_BIT_FPGA_FUNCTION0_IO_CHANGE_DIRECTION						4
#define STC_COM_BIT_FPGA_FUNCTION0_LED										5
#define STC_COM_BIT_FPGA_FUNCTION0_STATIC_MEMORY							6
#define STC_COM_BIT_FPGA_FUNCTION0_DISABLE_DIP_SW							7
#define STC_COM_BIT_FPGA_FUNCTION0_10BIT									8
#define STC_COM_BIT_FPGA_FUNCTION0_EXTERNAL_SDRAM							10
#define STC_COM_BIT_FPGA_FUNCTION0_12BIT									15
#define STC_COM_BIT_FPGA_FUNCTION1_CDS_GAIN_TYPE							0
#define STC_COM_BIT_FPGA_FUNCTION1_PHOTOCOUPLER								1
#define STC_COM_BIT_FPGA_FUNCTION1_TRIGGER_MASK								2
#define STC_COM_BIT_FPGA_FUNCTION1_GET_FPS									4
#define STC_COM_BIT_FPGA_FUNCTION1_V_BLANK_FOR_FPS							5
#define STC_COM_BIT_FPGA_FUNCTION1_MIRROR_HORIZONTAL						6
#define STC_COM_BIT_FPGA_FUNCTION1_MIRROR_VERTICAL							7
#define STC_COM_BIT_FPGA_FUNCTION1_AWB										8
#define STC_COM_BIT_FPGA_FUNCTION1_AGC										9
#define STC_COM_BIT_FPGA_FUNCTION1_AE										10
#define STC_COM_BIT_FPGA_FUNCTION1_IO_UNIT_US								11
#define STC_COM_BIT_FPGA_FUNCTION1_CMOS_RESET_TYPE_0						12
#define STC_COM_BIT_FPGA_FUNCTION1_DISABLED_READOUT							13
#define STC_COM_BIT_FPGA_FUNCTION1_GET_EXP_TIME								14
#define STC_COM_BIT_FPGA_FUNCTION1_GET_AE_TIME								15
#define STC_COM_BIT_FPGA_FUNCTION3_GET_MAX_EXP_INFO							0
#define STC_COM_BIT_FPGA_FUNCTION3_CDS_GAIN_TYPE2							1
#define STC_COM_BIT_FPGA_FUNCTION3_CDS_GAIN_TYPE3							2
#define STC_COM_BIT_FPGA_FUNCTION3_DIGITAL_CLAMP							7
#define STC_COM_BIT_FPGA_FUNCTION3_TRIGGER_VALID_OUT						8
#define STC_COM_BIT_FPGA_FUNCTION3_CAMERA_GAMMA								9
#define STC_COM_BIT_FPGA_FUNCTION3_STORE_CAMERA_SETTING						10
#define STC_COM_BIT_FPGA_FUNCTION3_DEFECT_PIXEL_CORRECTION					11
#define STC_COM_BIT_FPGA_FUNCTION3_DISABLE_MEMORY_TYPE_SELECTION			12
#define STC_COM_BIT_FPGA_FUNCTION3_H_BINNING_SUM							13
#define STC_COM_BIT_FPGA_FUNCTION3_DISABLE_EXPOSURE_START_WAIT_HD			14
#define STC_COM_BIT_FPGA_FUNCTION3_DISABLE_EXPOSURE_START_WAIT_READ_OUT		15
#define STC_COM_BIT_FPGA_FUNCTION4_U3V										0
#define STC_COM_BIT_FPGA_FUNCTION4_IO_EXISTENCE_FLAG						2
#define STC_COM_BIT_FPGA_FUNCTION4_IO_RESET_SW_DISABLED						4
#define STC_COM_BIT_FPGA_FUNCTION4_DISABLE_PULSE_WIDTH_EXPOSURE				5
#define STC_COM_BIT_FPGA_FUNCTION4_FPGA2_COMMAND							6
#define STC_COM_BIT_FPGA_FUNCTION4_COLOR_ARRAY_DOESNOT_DEPEND_ON_FLIPING	7
#define STC_COM_BIT_FPGA_FUNCTION4_CMOS_RESET_TYPE_1						8
#define STC_COM_BIT_FPGA_FUNCTION5_ENABLE_DEFECT_PIXEL_CORRECTION_COUNT		0
#define STC_COM_BIT_FPGA_FUNCTION6_IO0_EXISTENCE							0
#define STC_COM_BIT_FPGA_FUNCTION6_IO1_EXISTENCE							1
#define STC_COM_BIT_FPGA_FUNCTION6_IO2_EXISTENCE							2
#define STC_COM_BIT_FPGA_FUNCTION6_IO3_EXISTENCE							3
#define STC_COM_BIT_FPGA_FUNCTION7_SAME_PID_CAMERA_TYPE_0					0
#define STC_COM_BIT_FPGA_FUNCTION8_V_BINNING_SUM							3
#define STC_COM_BIT_FPGA_FUNCTION8_MAX_V_BINNING_FOR_FPS					5

#define STC_COM_BIT_FPGA2_FEATURE_1_EXPOSURE_TIME_BASE						30
#define STC_COM_BIT_FPGA2_FEATURE_3_RESET_SWITCH							3
#define STC_COM_BIT_FPGA2_FEATURE_3_RESET_SWITCH_CHANGE						4
#define STC_COM_BIT_FPGA2_FEATURE_5_ANALOG_BLACK_LEVEL						6
#define STC_COM_BIT_FPGA2_FEATURE_9_DISABLED_ANALOG_GAIN					4
#define STC_COM_BIT_FPGA2_FEATURE_9_GET_DIGITAL_GAIN_RANGE					6
#define STC_COM_BIT_FPGA2_FEATURE_9_DIGITAL_GAIN_TYPE						7
#define STC_COM_BIT_FPGA2_FEATURE_9_BLACK_LEVEL_MAX							8
#define STC_COM_BIT_FPGA2_FEATURE_9_DEVICE_TEMPERATURE_MAINBOARD			9
#define STC_COM_BIT_FPGA2_FEATURE_9_ADJUSTMENT_MODE_DIGITAL_GAIN			10
#define STC_COM_BIT_FPGA2_FEATURE_9_EXPOSURE_END_TRIGGER_SOURCE				12
#define STC_COM_BIT_FPGA2_FEATURE_9_FRAME_BURST_START						14
#define STC_COM_BIT_FPGA2_FEATURE_9_TRANSFER_END_OUT						15
#define STC_COM_BIT_FPGA2_FEATURE_A_LINE_DEBOUNCE_TIME						9
#define STC_COM_BIT_FPGA2_FEATURE_A_STCAM_CAMERA_FUNCTION_GENICAM_IO		12
#define STC_COM_BIT_FPGA2_FEATURE_A_EXPOSURE_TIME_OFFSET					24
#define STC_COM_BIT_FPGA2_FEATURE_C_TRIGGER_OVERLAP							12
#define STC_COM_BIT_FPGA2_FEATURE_C_TRIGGER_OVERLAP_OFF						13
#define STC_COM_BIT_FPGA2_FEATURE_C_TRIGGER_OVERLAP_READ_OUT				14
#define STC_COM_BIT_FPGA2_FEATURE_C_TRIGGER_OVERLAP_PREVIOUS_FRAME			15

#define STC_COM_BITMASK_FPGA_REFRESH				0x0001
#define STC_COM_BITMASK_FPGA_COUNTER_RESET			0x0002
#define STC_COM_BITMASK_FPGA_RO_CONTROL				0x0004
#define STC_COM_BITMASK_FPGA_SUBTRIGGER				0x4000
#define STC_COM_BITMASK_FPGA_H_FLIP					0x0001
#define STC_COM_BITMASK_FPGA_V_FLIP					0x0002
#define STC_COM_BITMASK_FPGA_IO0					0x0001
#define STC_COM_BITMASK_FPGA_IO1					0x0002
#define STC_COM_BITMASK_FPGA_IO2					0x0004
#define STC_COM_BITMASK_FPGA_IO3					0x0008
#define STC_COM_BITMASK_FPGA_TRIGGER_MODE			0x0003
#define STC_COM_BITMASK_FPGA_MEMORY_MODE			0x0030
#define STC_COM_BITMASK_FPGA_READOUT_SELECT			0x0040
#define STC_COM_BITMASK_FPGA_PACKET_SPLIT_MODE		0x0100
#define STC_COM_BITMASK_FPGA_TRG_IN_SELECT			0x0C00
#define STC_COM_BITMASK_FPGA_EXPOSURE_MODE			0x3000
#define STC_COM_BITMASK_FPGA_NEXT_H					0x4000
#define STC_COM_BITMASK_FPGA_COMPLETE_READOUT		0x8000
#define STC_COM_BITMASK_FPGA_TRIGGER_MASK			0x0001
#define STC_COM_BITMASK_FPGA_CMOS_RESET				0x0006
#define STC_COM_BITSHIFT_FPGA_IO0					0
#define STC_COM_BITSHIFT_FPGA_IO1					1
#define STC_COM_BITSHIFT_FPGA_IO2					2
#define STC_COM_BITSHIFT_FPGA_IO3					3
#define STC_COM_BITSHIFT_FPGA_TRIGGER_MODE			0
#define STC_COM_BITSHIFT_FPGA_MEMORY_MODE			4
#define STC_COM_BITSHIFT_FPGA_READOUT_SELECT		6
#define STC_COM_BITSHIFT_FPGA_PACKET_SPLIT_MODE		8
#define STC_COM_BITSHIFT_FPGA_TRG_IN_SELECT			10
#define STC_COM_BITSHIFT_FPGA_EXPOSURE_MODE			12
#define STC_COM_BITSHIFT_FPGA_NEXT_H				14
#define STC_COM_BITSHIFT_FPGA_COMPLETE_READOUT		15
#define STC_COM_BITSHIFT_FPGA_TRIGGER_MASK			0
#define STC_COM_BITSHIFT_FPGA_CMOS_RESET			1

#define STC_COM_VALUE_CAMERA_SETTING_INITIALIZE			0x8000
#define STC_COM_VALUE_CAMERA_SETTING_STANDARD_READ		0x1800
#define STC_COM_VALUE_CAMERA_SETTING_STANDARD_WRITE		0x2800
#define STC_COM_VALUE_CAMERA_SETTING_DEF_PIX_POS_READ	0x1400
#define STC_COM_VALUE_CAMERA_SETTING_DEF_PIX_POS_WRITE	0x2400

#define STC_COM_VALUE_SCAN_MODE_NORMAL						0x0000
#define STC_COM_VALUE_SCAN_MODE_PARTIAL_1					0x0004
#define STC_COM_VALUE_SCAN_MODE_PARTIAL_2					0x0001
#define STC_COM_VALUE_SCAN_MODE_PARTIAL_4					0x0002
#define STC_COM_VALUE_SCAN_MODE_VARIABLE_PARTIAL			0x0008
#define STC_COM_VALUE_SCAN_MODE_BINNING						0x0010
#define STC_COM_VALUE_SCAN_MODE_BINNING_PARTIAL_1			0x0020
#define STC_COM_VALUE_SCAN_MODE_BINNING_PARTIAL_2			0x0040
#define STC_COM_VALUE_SCAN_MODE_BINNING_PARTIAL_4			0x0080
#define STC_COM_VALUE_SCAN_MODE_BINNING_VARIABLE_PARTIAL	0x0100
#define STC_COM_VALUE_SCAN_MODE_ROI							0x8000

#define STC_COM_VALUE_DECIMATION_BINNING_0_0		0x00
#define STC_COM_VALUE_DECIMATION_BINNING_1_0		0x10
#define STC_COM_VALUE_DECIMATION_BINNING_1_1		0x11
#define STC_COM_VALUE_DECIMATION_BINNING_1_2		0x12
#define STC_COM_VALUE_DECIMATION_BINNING_1_4		0x14
#define STC_COM_VALUE_DECIMATION_BINNING_2_0		0x20
#define STC_COM_VALUE_DECIMATION_BINNING_2_1		0x21
#define STC_COM_VALUE_DECIMATION_BINNING_2_2		0x22
#define STC_COM_VALUE_DECIMATION_BINNING_3_0		0x30
#define STC_COM_VALUE_DECIMATION_BINNING_3_1		0x31
#define STC_COM_VALUE_DECIMATION_BINNING_3_3		0x33
#define STC_COM_VALUE_DECIMATION_BINNING_4_0		0x40
#define STC_COM_VALUE_DECIMATION_BINNING_4_1		0x41
#define STC_COM_VALUE_DECIMATION_BINNING_4_2		0x42
#define STC_COM_VALUE_DECIMATION_BINNING_5_0		0x50
#define STC_COM_VALUE_DECIMATION_BINNING_5_1		0x51
#define STC_COM_VALUE_DECIMATION_BINNING_6_0		0x60
#define STC_COM_VALUE_DECIMATION_BINNING_7_0		0x70
#define STC_COM_VALUE_DECIMATION_BINNING_7_1		0x71
#define STC_COM_VALUE_DECIMATION_BINNING_7_3		0x73

#define STC_COM_BITMASK_DECIMATION_BINNING_NONE		0x00000000
#define STC_COM_BITMASK_DECIMATION_BINNING_0_0		0x00000001
#define STC_COM_BITMASK_DECIMATION_BINNING_1_0		0x00000002
#define STC_COM_BITMASK_DECIMATION_BINNING_1_1		0x00000004
#define STC_COM_BITMASK_DECIMATION_BINNING_1_2		0x00000008
#define STC_COM_BITMASK_DECIMATION_BINNING_1_4		0x00000010
#define STC_COM_BITMASK_DECIMATION_BINNING_2_0		0x00000020
#define STC_COM_BITMASK_DECIMATION_BINNING_2_1		0x00000040
#define STC_COM_BITMASK_DECIMATION_BINNING_2_2		0x00000080
#define STC_COM_BITMASK_DECIMATION_BINNING_3_0		0x00000100
#define STC_COM_BITMASK_DECIMATION_BINNING_3_1		0x00000200
#define STC_COM_BITMASK_DECIMATION_BINNING_3_3		0x00000400
#define STC_COM_BITMASK_DECIMATION_BINNING_4_0		0x00000800
#define STC_COM_BITMASK_DECIMATION_BINNING_4_1		0x00001000
#define STC_COM_BITMASK_DECIMATION_BINNING_4_2		0x00002000
#define STC_COM_BITMASK_DECIMATION_BINNING_5_0		0x00004000
#define STC_COM_BITMASK_DECIMATION_BINNING_5_1		0x00008000
#define STC_COM_BITMASK_DECIMATION_BINNING_6_0		0x00010000
#define STC_COM_BITMASK_DECIMATION_BINNING_7_0		0x00020000
#define STC_COM_BITMASK_DECIMATION_BINNING_7_1		0x00040000
#define STC_COM_BITMASK_DECIMATION_BINNING_7_3		0x00080000

#define STC_COM_BITMASK_SENSOR_SHUTTER_GLOBAL_RESET	0x0001
#define STC_COM_BITMASK_SENSOR_SHUTTER_GLOBAL		0x0002

#define STC_COM_VALUE_BINNINGSUM_MODE_OFF		0x0000
#define STC_COM_VALUE_BINNINGSUM_MODE_H_ON		0x0001
#define STC_COM_VALUE_BINNINGSUM_MODE_V_ON		0x0101

#define STC_COM_VALUE_CLOCK_NORMAL		0x00000000
#define STC_COM_VALUE_CLOCK_DIV_2		0x00000001
#define STC_COM_VALUE_CLOCK_DIV_4		0x00000002
#define STC_COM_VALUE_CLOCK_VGA_90FPS	0x00000100

#define STC_COM_VALUE_EXPOSURE_MODE_OFF					0
#define STC_COM_VALUE_EXPOSURE_MODE_TIMED				1
#define STC_COM_VALUE_EXPOSURE_MODE_TRIGGER_WIDTH		2
#define STC_COM_VALUE_EXPOSURE_MODE_TRIGGER_CONTROLLED	3

#define STC_COM_VALUE_SENSOR_SHUTTER_MODE_ROLLING		0
#define STC_COM_VALUE_SENSOR_SHUTTER_MODE_GLOBAL_RESET	1
#define STC_COM_VALUE_SENSOR_SHUTTER_MODE_GLOBAL		2

#define STC_COM_VALUE_OUT_DISABLE						0x00
#define STC_COM_VALUE_OUT_GENERAL_OUTPUT				0x01
#define STC_COM_VALUE_OUT_TRIGGER_OUTPUT_PROGRAMMABLE	0x10
#define STC_COM_VALUE_OUT_TRIGGER_OUTPUT_LOOP_THROUGH	0x11
#define STC_COM_VALUE_OUT_EXPOSURE_END					0x12
#define STC_COM_VALUE_OUT_CCD_READ_END_OUTPUT			0x13
#define STC_COM_VALUE_OUT_STROBE_OUTPUT_PROGRAMMABLE	0x20
#define STC_COM_VALUE_OUT_STROBE_OUTPUT_EXPOSURE		0x21
#define STC_COM_VALUE_OUT_TRIGGER_VALID_OUT				0x14
#define STC_COM_VALUE_OUT_TRANSFER_END					0x15
#define STC_COM_VALUE_IN_DISABLE						0x00
#define STC_COM_VALUE_IN_GENERAL_INPUT					0x01
#define STC_COM_VALUE_IN_TRIGGER_INPUT					0x10
#define STC_COM_VALUE_IN_READOUT_INPUT					0x30
#define STC_COM_VALUE_IN_SUB_TRIGGER_INPUT				0x40

#define STC_COM_VALUE_TRANSFER_BITS_PER_PIXEL_RAW_08		0x00000001
#define STC_COM_VALUE_TRANSFER_BITS_PER_PIXEL_RAW_10		0x00000002
#define STC_COM_VALUE_TRANSFER_BITS_PER_PIXEL_RAW_10P		0x00010000
#define STC_COM_VALUE_TRANSFER_BITS_PER_PIXEL_RAW_12		0x00000004
#define STC_COM_VALUE_TRANSFER_BITS_PER_PIXEL_RAW_12P		0x00020000
#define STC_COM_VALUE_TRANSFER_BITS_PER_PIXEL_MONO_08		0x00000020
#define STC_COM_VALUE_TRANSFER_BITS_PER_PIXEL_MONO_10		0x00000040
#define STC_COM_VALUE_TRANSFER_BITS_PER_PIXEL_MONO_10P		0x00100000
#define STC_COM_VALUE_TRANSFER_BITS_PER_PIXEL_MONO_12		0x00000080
#define STC_COM_VALUE_TRANSFER_BITS_PER_PIXEL_MONO_12P		0x00200000
#define STC_COM_VALUE_TRANSFER_BITS_PER_PIXEL_BGR_08		0x00000400
#define STC_COM_VALUE_TRANSFER_BITS_PER_PIXEL_BGR_10		0x00000800

#define MACRO_GET_CAM_VALUE_16(__PTR__, __ADR__) ( ddata->__PTR__[__ADR__] | ((ddata->__PTR__[__ADR__ + 1] << 8) & 0xff00))
#define MACRO_GET_CAM_VALUE_32(__PTR__, __ADR__) ( ddata->__PTR__[__ADR__] | ((ddata->__PTR__[__ADR__ + 1] << 8) & 0x0000ff00) | ((ddata->__PTR__[__ADR__ + 2] << 16) & 0x00ff0000) | ((ddata->__PTR__[__ADR__ + 3] << 24) & 0xff000000))
#define MACRO_SET_CAM_VALUE_16(__PTR__, __ADR__, __VALUE__) ddata->__PTR__[__ADR__] = __VALUE__ & 0x00ff; \
												 ddata->__PTR__[__ADR__ + 1] = __VALUE__ >> 8 & 0x00ff;
#define MACRO_SET_CAM_VALUE_32(__PTR__, __ADR__, __VALUE__) ddata->__PTR__[__ADR__] = __VALUE__ & 0x00ff; \
												 ddata->__PTR__[__ADR__ + 1] = __VALUE__ >> 8 & 0x00ff; \
												 ddata->__PTR__[__ADR__ + 2] = __VALUE__ >> 16 & 0x00ff; \
												 ddata->__PTR__[__ADR__ + 3] = __VALUE__ >> 24 & 0x00ff;

#endif//__STCAM_DD_CAM_DEF_H__
