/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QPushButton *mainCapture;
    QTabWidget *tabWidget;
    QWidget *ShutterGain;
    QSlider *sgExposureSlider;
    QLabel *label0101;
    QLineEdit *sgExposureEdit;
    QLabel *label0102;
    QLabel *label0103;
    QLabel *label0104;
    QLabel *label0105;
    QLabel *label0106;
    QLabel *label0107;
    QLabel *label0108;
    QLabel *label0109;
    QLabel *label0110;
    QSlider *sgAnalogGainSlider;
    QSlider *sgDigitalGainSlider;
    QSlider *sgAlcTargetSlider;
    QSlider *sgMaxExposureSlider;
    QSlider *sgMinExposureSlider;
    QSlider *sgMinGainSlider;
    QSlider *sgMaxGainSlider;
    QLineEdit *sgAnalogGainEdit;
    QLineEdit *sgDigitalGainEdit;
    QLineEdit *sgAlcTargetEdit;
    QLineEdit *sgMinExposureEdit;
    QLineEdit *sgMaxExposureEdit;
    QLineEdit *sgMinGainEdit;
    QLineEdit *sgMaxGainEdit;
    QComboBox *sgAlcMode;
    QComboBox *sgAdjustGain;
    QLineEdit *sgExposure;
    QLineEdit *sgAnalogGain;
    QLineEdit *sgDigitalGain;
    QLineEdit *sgMinExposure;
    QLineEdit *sgMaxExposure;
    QLineEdit *sgMinGain;
    QLineEdit *sgMaxGain;
    QWidget *WhiteBalance;
    QLabel *label0201;
    QLabel *label0202;
    QLabel *label0203;
    QLabel *label0204;
    QLabel *label0205;
    QLabel *label0206;
    QLabel *label0207;
    QLabel *label0208;
    QLabel *label0209;
    QLabel *label0211;
    QLabel *label0210;
    QLabel *label0212;
    QSlider *wbRGainSlider;
    QSlider *wbGrGainSlider;
    QSlider *wbGbGainSlider;
    QSlider *wbBGainSlider;
    QSlider *wbSaturationSlider;
    QSlider *wbHueSlider;
    QSlider *wbHcsStartSlider;
    QSlider *wbLcsStartSlider;
    QSlider *wbHcsSuppressionSlider;
    QSlider *wbLcsSuppressionSlider;
    QComboBox *wbMode;
    QComboBox *wbHSMode;
    QLineEdit *wbRGainEdit;
    QLineEdit *wbGrGainEdit;
    QLineEdit *wbGbGainEdit;
    QLineEdit *wbBGainEdit;
    QLineEdit *wbHueEdit;
    QLineEdit *wbHcsStartEdit;
    QLineEdit *wbHcsSuppressionEdit;
    QLineEdit *wbLcsStartEdit;
    QLineEdit *wbLcsSuppressionEdit;
    QLineEdit *wbSaturationEdit;
    QLineEdit *wbRGain;
    QLineEdit *wbGrGain;
    QLineEdit *wbGbGain;
    QLineEdit *wbBGain;
    QLineEdit *wbHue;
    QLineEdit *wbSaturation;
    QWidget *Y;
    QLabel *label0301;
    QLabel *label0302;
    QLabel *label0303;
    QLabel *label0304;
    QLabel *label0305;
    QLabel *label0306;
    QLabel *label0307;
    QLabel *label0308;
    QLabel *label0309;
    QLabel *label0310;
    QSlider *yGammaValueSlider;
    QSlider *yCameraGammaSlider;
    QSlider *ySharpnessgainSlider;
    QSlider *ySharpnessCoringSlider;
    QSlider *yDigitalClampSlider;
    QSlider *yAnalogBlackLevelSlider;
    QSlider *yShadingTargetSlider;
    QComboBox *yGammaMode;
    QComboBox *yShadingMode;
    QComboBox *ySharpnessMode;
    QLineEdit *yGammaValue;
    QLineEdit *yCameraGamma;
    QLineEdit *ySharpnessgain;
    QLineEdit *ySharpnessCoring;
    QLineEdit *yDigitalClamp;
    QLineEdit *yAnalogBlackLevel;
    QLineEdit *yShadingTarget;
    QWidget *ColorGamma;
    QLabel *label0401;
    QLabel *label0402;
    QLabel *label0403;
    QLabel *label0404;
    QLabel *label0405;
    QLabel *label0406;
    QLabel *label0407;
    QLabel *label0408;
    QSlider *cgRGammaValueSlider;
    QSlider *cgGrGammaValueSlider;
    QSlider *cgGbGammaValueSlider;
    QSlider *cgBGammaValueSlider;
    QComboBox *cgRGammaMode;
    QComboBox *cgGrGammaMode;
    QComboBox *cgGbGammaMode;
    QComboBox *cgBGammaMode;
    QLineEdit *cgRGammaValue;
    QLineEdit *cgGrGammaValue;
    QLineEdit *cgGbGammaValue;
    QLineEdit *cgBGammaValue;
    QWidget *TriggerMode;
    QLabel *label0501;
    QLabel *label0502;
    QLabel *label0503;
    QLabel *label0504;
    QLabel *label0505;
    QLabel *label0506;
    QLabel *label0507;
    QLabel *label0511;
    QLabel *label0508;
    QLabel *label0509;
    QLabel *label0510;
    QComboBox *tmExposureMode;
    QComboBox *tmTriggerSelect;
    QComboBox *tmTriggerMode;
    QComboBox *tmTriggerSource;
    QComboBox *tmTriggerOverlap;
    QComboBox *tmNoiseReduction;
    QComboBox *tmWaitHd;
    QComboBox *tmWaitReadOut;
    QComboBox *tmShutterMode;
    QSlider *tmTriggerDelaySlider;
    QSlider *tmAutoExposureEndSlider;
    QLineEdit *tmTriggerDelayEdit;
    QLineEdit *tmAutoExposureEndEdit;
    QPushButton *tmFrameStart;
    QPushButton *tmExposureStart;
    QPushButton *tmExposureEnd;
    QPushButton *tmReadOut;
    QCheckBox *tmAutoExposureEndCheck;
    QLineEdit *tmTriggerDelay;
    QWidget *TriggerTiming;
    QLabel *label0601;
    QSlider *ttStrobeStartSlider;
    QLineEdit *ttStrobeStartEdit;
    QLabel *label0602;
    QLabel *label0603;
    QLabel *label0604;
    QLabel *label0605;
    QLabel *label0606;
    QSlider *ttStrobeEndSlider;
    QSlider *ttPulseDelaySlider;
    QSlider *ttPulseDurationSlider;
    QSlider *ttReadOutSlider;
    QSlider *ttLineDebounceSlider;
    QLineEdit *ttStrobeEndEdit;
    QLineEdit *ttPulseDelayEdit;
    QLineEdit *ttPulseDurationEdit;
    QLineEdit *ttReadOutEdit;
    QLineEdit *ttLineDebounceEdit;
    QLineEdit *ttStrobeStart;
    QLineEdit *ttStrobeEnd;
    QLineEdit *ttPulseDelay;
    QLineEdit *ttPulseDuration;
    QLineEdit *ttReadOut;
    QLineEdit *ttLineDebounce;
    QWidget *IO;
    QLabel *label0701;
    QLabel *label0702;
    QLabel *label0703;
    QLabel *label0709;
    QLabel *label0705;
    QLabel *label0706;
    QLabel *label0707;
    QLabel *label0708;
    QLabel *label0704;
    QLabel *label0710;
    QLabel *label0711;
    QComboBox *io0InOut;
    QComboBox *io1InOut;
    QComboBox *io3Status;
    QComboBox *io3NegaPosi;
    QComboBox *io2Mode;
    QComboBox *io2InOut;
    QComboBox *io2Status;
    QComboBox *io2NegaPosi;
    QComboBox *io0Status;
    QComboBox *io3Mode;
    QComboBox *io1Mode;
    QComboBox *io1Status;
    QComboBox *io0NegaPosi;
    QComboBox *io0Mode;
    QComboBox *io1NegaPosi;
    QComboBox *io3InOut;
    QComboBox *ioResetSwitch;
    QComboBox *ioLed;
    QLabel *label0714;
    QLineEdit *ioSw0;
    QLineEdit *ioSw1;
    QLineEdit *ioSw2;
    QLineEdit *ioSw3;
    QLineEdit *ioTemperature;
    QPushButton *ioResetCounter;
    QPushButton *ioClearBuffer;
    QWidget *HDR;
    QLabel *label0801;
    QLabel *label0802;
    QLabel *label0803;
    QLabel *label0804;
    QLabel *label0805;
    QLabel *label0806;
    QComboBox *hdrMode;
    QComboBox *hdrSlope;
    QSlider *hdrKnee1Slider;
    QSlider *hdrVlow2Slider;
    QSlider *hdrKnee2Slider;
    QSlider *hdrVlow3Slider;
    QLineEdit *hdrKnee1Edit;
    QLineEdit *hdrVlow2Edit;
    QLineEdit *hdrKnee2Edit;
    QLineEdit *hdrVlow3Edit;
    QWidget *EEPROM;
    QPushButton *eepLoadStandard;
    QPushButton *eepSaveStandard;
    QPushButton *eepReset;
    QPushButton *eepLoadDpp;
    QPushButton *eepSaveDpp;
    QWidget *Other;
    QLabel *label1001;
    QLabel *label1002;
    QLabel *label1004;
    QLabel *label1005;
    QLabel *label1007;
    QLabel *label1008;
    QLabel *label1009;
    QLabel *label1010;
    QLabel *label1012;
    QLabel *label1011;
    QLabel *label1013;
    QLabel *label1014;
    QLabel *label1015;
    QLabel *label1016;
    QLabel *label1017;
    QLabel *label1006;
    QComboBox *otScanMode;
    QComboBox *otBinSum;
    QComboBox *otRegion;
    QComboBox *otRegionMode;
    QComboBox *otTransferBits;
    QComboBox *otDisplayPixFormat;
    QComboBox *otColorInterpolation;
    QComboBox *otRotationMode;
    QComboBox *otClock;
    QSlider *otOffsetXSlider;
    QSlider *otWidthSlider;
    QSlider *otOffsetYSlider;
    QSlider *otHeightSlider;
    QSlider *otVBlankSlider;
    QLineEdit *otOffsetXEdit;
    QLineEdit *otWidthEdit;
    QLineEdit *otOffsetYEdit;
    QLineEdit *otHeightEdit;
    QLineEdit *otVBlankEdit;
    QLabel *label1003;
    QComboBox *otMirrorMode;
    QLineEdit *otFps;
    QLabel *label1017_2;
    QComboBox *otHDeciBin;
    QComboBox *otVDeciBin;
    QLabel *label0001;
    QLabel *label0002;
    QLabel *label0003;
    QLabel *label0004;
    QLabel *label0005;
    QLineEdit *mainCamera;
    QLineEdit *mainFpga;
    QLineEdit *mainFirm;
    QLineEdit *mainDriver;
    QLineEdit *mainLibrary;
    QPushButton *mainCameraId;
    QPushButton *mainSettingFile;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(766, 589);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        mainCapture = new QPushButton(centralWidget);
        mainCapture->setObjectName(QStringLiteral("mainCapture"));
        mainCapture->setGeometry(QRect(30, 10, 111, 31));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(170, 10, 591, 511));
        ShutterGain = new QWidget();
        ShutterGain->setObjectName(QStringLiteral("ShutterGain"));
        ShutterGain->setContextMenuPolicy(Qt::DefaultContextMenu);
        sgExposureSlider = new QSlider(ShutterGain);
        sgExposureSlider->setObjectName(QStringLiteral("sgExposureSlider"));
        sgExposureSlider->setGeometry(QRect(150, 10, 160, 29));
        sgExposureSlider->setOrientation(Qt::Horizontal);
        label0101 = new QLabel(ShutterGain);
        label0101->setObjectName(QStringLiteral("label0101"));
        label0101->setGeometry(QRect(36, 20, 71, 20));
        sgExposureEdit = new QLineEdit(ShutterGain);
        sgExposureEdit->setObjectName(QStringLiteral("sgExposureEdit"));
        sgExposureEdit->setEnabled(true);
        sgExposureEdit->setGeometry(QRect(460, 10, 91, 27));
        label0102 = new QLabel(ShutterGain);
        label0102->setObjectName(QStringLiteral("label0102"));
        label0102->setGeometry(QRect(30, 60, 91, 20));
        label0103 = new QLabel(ShutterGain);
        label0103->setObjectName(QStringLiteral("label0103"));
        label0103->setGeometry(QRect(30, 100, 91, 20));
        label0104 = new QLabel(ShutterGain);
        label0104->setObjectName(QStringLiteral("label0104"));
        label0104->setGeometry(QRect(36, 140, 91, 20));
        label0105 = new QLabel(ShutterGain);
        label0105->setObjectName(QStringLiteral("label0105"));
        label0105->setGeometry(QRect(36, 180, 81, 20));
        label0106 = new QLabel(ShutterGain);
        label0106->setObjectName(QStringLiteral("label0106"));
        label0106->setGeometry(QRect(16, 220, 121, 20));
        label0107 = new QLabel(ShutterGain);
        label0107->setObjectName(QStringLiteral("label0107"));
        label0107->setGeometry(QRect(16, 260, 121, 20));
        label0108 = new QLabel(ShutterGain);
        label0108->setObjectName(QStringLiteral("label0108"));
        label0108->setGeometry(QRect(20, 300, 111, 20));
        label0109 = new QLabel(ShutterGain);
        label0109->setObjectName(QStringLiteral("label0109"));
        label0109->setGeometry(QRect(20, 340, 101, 20));
        label0110 = new QLabel(ShutterGain);
        label0110->setObjectName(QStringLiteral("label0110"));
        label0110->setGeometry(QRect(10, 380, 171, 20));
        sgAnalogGainSlider = new QSlider(ShutterGain);
        sgAnalogGainSlider->setObjectName(QStringLiteral("sgAnalogGainSlider"));
        sgAnalogGainSlider->setGeometry(QRect(150, 60, 160, 29));
        sgAnalogGainSlider->setOrientation(Qt::Horizontal);
        sgDigitalGainSlider = new QSlider(ShutterGain);
        sgDigitalGainSlider->setObjectName(QStringLiteral("sgDigitalGainSlider"));
        sgDigitalGainSlider->setGeometry(QRect(150, 100, 160, 29));
        sgDigitalGainSlider->setOrientation(Qt::Horizontal);
        sgAlcTargetSlider = new QSlider(ShutterGain);
        sgAlcTargetSlider->setObjectName(QStringLiteral("sgAlcTargetSlider"));
        sgAlcTargetSlider->setGeometry(QRect(150, 180, 160, 29));
        sgAlcTargetSlider->setOrientation(Qt::Horizontal);
        sgMaxExposureSlider = new QSlider(ShutterGain);
        sgMaxExposureSlider->setObjectName(QStringLiteral("sgMaxExposureSlider"));
        sgMaxExposureSlider->setGeometry(QRect(150, 260, 160, 29));
        sgMaxExposureSlider->setOrientation(Qt::Horizontal);
        sgMinExposureSlider = new QSlider(ShutterGain);
        sgMinExposureSlider->setObjectName(QStringLiteral("sgMinExposureSlider"));
        sgMinExposureSlider->setGeometry(QRect(150, 220, 160, 29));
        sgMinExposureSlider->setOrientation(Qt::Horizontal);
        sgMinGainSlider = new QSlider(ShutterGain);
        sgMinGainSlider->setObjectName(QStringLiteral("sgMinGainSlider"));
        sgMinGainSlider->setGeometry(QRect(150, 290, 160, 29));
        sgMinGainSlider->setOrientation(Qt::Horizontal);
        sgMaxGainSlider = new QSlider(ShutterGain);
        sgMaxGainSlider->setObjectName(QStringLiteral("sgMaxGainSlider"));
        sgMaxGainSlider->setGeometry(QRect(150, 330, 160, 29));
        sgMaxGainSlider->setOrientation(Qt::Horizontal);
        sgAnalogGainEdit = new QLineEdit(ShutterGain);
        sgAnalogGainEdit->setObjectName(QStringLiteral("sgAnalogGainEdit"));
        sgAnalogGainEdit->setGeometry(QRect(460, 60, 91, 27));
        sgDigitalGainEdit = new QLineEdit(ShutterGain);
        sgDigitalGainEdit->setObjectName(QStringLiteral("sgDigitalGainEdit"));
        sgDigitalGainEdit->setGeometry(QRect(460, 100, 91, 27));
        sgAlcTargetEdit = new QLineEdit(ShutterGain);
        sgAlcTargetEdit->setObjectName(QStringLiteral("sgAlcTargetEdit"));
        sgAlcTargetEdit->setGeometry(QRect(460, 180, 91, 27));
        sgMinExposureEdit = new QLineEdit(ShutterGain);
        sgMinExposureEdit->setObjectName(QStringLiteral("sgMinExposureEdit"));
        sgMinExposureEdit->setGeometry(QRect(460, 220, 91, 27));
        sgMaxExposureEdit = new QLineEdit(ShutterGain);
        sgMaxExposureEdit->setObjectName(QStringLiteral("sgMaxExposureEdit"));
        sgMaxExposureEdit->setGeometry(QRect(460, 260, 91, 27));
        sgMinGainEdit = new QLineEdit(ShutterGain);
        sgMinGainEdit->setObjectName(QStringLiteral("sgMinGainEdit"));
        sgMinGainEdit->setGeometry(QRect(460, 300, 91, 27));
        sgMaxGainEdit = new QLineEdit(ShutterGain);
        sgMaxGainEdit->setObjectName(QStringLiteral("sgMaxGainEdit"));
        sgMaxGainEdit->setGeometry(QRect(460, 340, 91, 27));
        sgAlcMode = new QComboBox(ShutterGain);
        sgAlcMode->setObjectName(QStringLiteral("sgAlcMode"));
        sgAlcMode->setGeometry(QRect(194, 140, 121, 27));
        sgAdjustGain = new QComboBox(ShutterGain);
        sgAdjustGain->setObjectName(QStringLiteral("sgAdjustGain"));
        sgAdjustGain->setGeometry(QRect(194, 380, 121, 27));
        sgExposure = new QLineEdit(ShutterGain);
        sgExposure->setObjectName(QStringLiteral("sgExposure"));
        sgExposure->setEnabled(false);
        sgExposure->setGeometry(QRect(350, 10, 91, 27));
        sgAnalogGain = new QLineEdit(ShutterGain);
        sgAnalogGain->setObjectName(QStringLiteral("sgAnalogGain"));
        sgAnalogGain->setEnabled(false);
        sgAnalogGain->setGeometry(QRect(350, 60, 91, 27));
        sgDigitalGain = new QLineEdit(ShutterGain);
        sgDigitalGain->setObjectName(QStringLiteral("sgDigitalGain"));
        sgDigitalGain->setEnabled(false);
        sgDigitalGain->setGeometry(QRect(350, 100, 91, 27));
        sgMinExposure = new QLineEdit(ShutterGain);
        sgMinExposure->setObjectName(QStringLiteral("sgMinExposure"));
        sgMinExposure->setEnabled(false);
        sgMinExposure->setGeometry(QRect(350, 220, 91, 27));
        sgMaxExposure = new QLineEdit(ShutterGain);
        sgMaxExposure->setObjectName(QStringLiteral("sgMaxExposure"));
        sgMaxExposure->setEnabled(false);
        sgMaxExposure->setGeometry(QRect(350, 260, 91, 27));
        sgMinGain = new QLineEdit(ShutterGain);
        sgMinGain->setObjectName(QStringLiteral("sgMinGain"));
        sgMinGain->setEnabled(false);
        sgMinGain->setGeometry(QRect(350, 300, 91, 27));
        sgMaxGain = new QLineEdit(ShutterGain);
        sgMaxGain->setObjectName(QStringLiteral("sgMaxGain"));
        sgMaxGain->setEnabled(false);
        sgMaxGain->setGeometry(QRect(350, 340, 91, 27));
        tabWidget->addTab(ShutterGain, QString());
        WhiteBalance = new QWidget();
        WhiteBalance->setObjectName(QStringLiteral("WhiteBalance"));
        label0201 = new QLabel(WhiteBalance);
        label0201->setObjectName(QStringLiteral("label0201"));
        label0201->setGeometry(QRect(30, 10, 67, 17));
        label0202 = new QLabel(WhiteBalance);
        label0202->setObjectName(QStringLiteral("label0202"));
        label0202->setGeometry(QRect(30, 50, 67, 17));
        label0203 = new QLabel(WhiteBalance);
        label0203->setObjectName(QStringLiteral("label0203"));
        label0203->setGeometry(QRect(30, 80, 67, 17));
        label0204 = new QLabel(WhiteBalance);
        label0204->setObjectName(QStringLiteral("label0204"));
        label0204->setGeometry(QRect(30, 110, 67, 17));
        label0205 = new QLabel(WhiteBalance);
        label0205->setObjectName(QStringLiteral("label0205"));
        label0205->setGeometry(QRect(30, 140, 67, 17));
        label0206 = new QLabel(WhiteBalance);
        label0206->setObjectName(QStringLiteral("label0206"));
        label0206->setGeometry(QRect(30, 170, 161, 17));
        label0207 = new QLabel(WhiteBalance);
        label0207->setObjectName(QStringLiteral("label0207"));
        label0207->setGeometry(QRect(30, 200, 67, 17));
        label0208 = new QLabel(WhiteBalance);
        label0208->setObjectName(QStringLiteral("label0208"));
        label0208->setGeometry(QRect(30, 230, 81, 17));
        label0209 = new QLabel(WhiteBalance);
        label0209->setObjectName(QStringLiteral("label0209"));
        label0209->setGeometry(QRect(30, 260, 261, 17));
        label0211 = new QLabel(WhiteBalance);
        label0211->setObjectName(QStringLiteral("label0211"));
        label0211->setGeometry(QRect(30, 360, 261, 17));
        label0210 = new QLabel(WhiteBalance);
        label0210->setObjectName(QStringLiteral("label0210"));
        label0210->setGeometry(QRect(30, 310, 311, 17));
        label0212 = new QLabel(WhiteBalance);
        label0212->setObjectName(QStringLiteral("label0212"));
        label0212->setGeometry(QRect(30, 410, 301, 17));
        wbRGainSlider = new QSlider(WhiteBalance);
        wbRGainSlider->setObjectName(QStringLiteral("wbRGainSlider"));
        wbRGainSlider->setGeometry(QRect(170, 40, 160, 29));
        wbRGainSlider->setOrientation(Qt::Horizontal);
        wbGrGainSlider = new QSlider(WhiteBalance);
        wbGrGainSlider->setObjectName(QStringLiteral("wbGrGainSlider"));
        wbGrGainSlider->setGeometry(QRect(170, 70, 160, 29));
        wbGrGainSlider->setOrientation(Qt::Horizontal);
        wbGbGainSlider = new QSlider(WhiteBalance);
        wbGbGainSlider->setObjectName(QStringLiteral("wbGbGainSlider"));
        wbGbGainSlider->setGeometry(QRect(170, 100, 160, 29));
        wbGbGainSlider->setOrientation(Qt::Horizontal);
        wbBGainSlider = new QSlider(WhiteBalance);
        wbBGainSlider->setObjectName(QStringLiteral("wbBGainSlider"));
        wbBGainSlider->setGeometry(QRect(170, 130, 160, 29));
        wbBGainSlider->setOrientation(Qt::Horizontal);
        wbSaturationSlider = new QSlider(WhiteBalance);
        wbSaturationSlider->setObjectName(QStringLiteral("wbSaturationSlider"));
        wbSaturationSlider->setGeometry(QRect(170, 220, 160, 29));
        wbSaturationSlider->setOrientation(Qt::Horizontal);
        wbHueSlider = new QSlider(WhiteBalance);
        wbHueSlider->setObjectName(QStringLiteral("wbHueSlider"));
        wbHueSlider->setGeometry(QRect(170, 190, 160, 29));
        wbHueSlider->setOrientation(Qt::Horizontal);
        wbHcsStartSlider = new QSlider(WhiteBalance);
        wbHcsStartSlider->setObjectName(QStringLiteral("wbHcsStartSlider"));
        wbHcsStartSlider->setGeometry(QRect(170, 280, 160, 29));
        wbHcsStartSlider->setOrientation(Qt::Horizontal);
        wbLcsStartSlider = new QSlider(WhiteBalance);
        wbLcsStartSlider->setObjectName(QStringLiteral("wbLcsStartSlider"));
        wbLcsStartSlider->setGeometry(QRect(170, 380, 160, 29));
        wbLcsStartSlider->setOrientation(Qt::Horizontal);
        wbHcsSuppressionSlider = new QSlider(WhiteBalance);
        wbHcsSuppressionSlider->setObjectName(QStringLiteral("wbHcsSuppressionSlider"));
        wbHcsSuppressionSlider->setGeometry(QRect(170, 330, 160, 29));
        wbHcsSuppressionSlider->setOrientation(Qt::Horizontal);
        wbLcsSuppressionSlider = new QSlider(WhiteBalance);
        wbLcsSuppressionSlider->setObjectName(QStringLiteral("wbLcsSuppressionSlider"));
        wbLcsSuppressionSlider->setGeometry(QRect(170, 430, 160, 29));
        wbLcsSuppressionSlider->setOrientation(Qt::Horizontal);
        wbMode = new QComboBox(WhiteBalance);
        wbMode->setObjectName(QStringLiteral("wbMode"));
        wbMode->setGeometry(QRect(190, 10, 141, 27));
        wbHSMode = new QComboBox(WhiteBalance);
        wbHSMode->setObjectName(QStringLiteral("wbHSMode"));
        wbHSMode->setGeometry(QRect(194, 160, 141, 27));
        wbRGainEdit = new QLineEdit(WhiteBalance);
        wbRGainEdit->setObjectName(QStringLiteral("wbRGainEdit"));
        wbRGainEdit->setGeometry(QRect(460, 40, 113, 27));
        wbGrGainEdit = new QLineEdit(WhiteBalance);
        wbGrGainEdit->setObjectName(QStringLiteral("wbGrGainEdit"));
        wbGrGainEdit->setGeometry(QRect(460, 70, 113, 27));
        wbGbGainEdit = new QLineEdit(WhiteBalance);
        wbGbGainEdit->setObjectName(QStringLiteral("wbGbGainEdit"));
        wbGbGainEdit->setGeometry(QRect(460, 100, 113, 27));
        wbBGainEdit = new QLineEdit(WhiteBalance);
        wbBGainEdit->setObjectName(QStringLiteral("wbBGainEdit"));
        wbBGainEdit->setGeometry(QRect(460, 130, 113, 27));
        wbHueEdit = new QLineEdit(WhiteBalance);
        wbHueEdit->setObjectName(QStringLiteral("wbHueEdit"));
        wbHueEdit->setGeometry(QRect(460, 190, 113, 27));
        wbHcsStartEdit = new QLineEdit(WhiteBalance);
        wbHcsStartEdit->setObjectName(QStringLiteral("wbHcsStartEdit"));
        wbHcsStartEdit->setGeometry(QRect(460, 280, 113, 27));
        wbHcsSuppressionEdit = new QLineEdit(WhiteBalance);
        wbHcsSuppressionEdit->setObjectName(QStringLiteral("wbHcsSuppressionEdit"));
        wbHcsSuppressionEdit->setGeometry(QRect(460, 320, 113, 27));
        wbLcsStartEdit = new QLineEdit(WhiteBalance);
        wbLcsStartEdit->setObjectName(QStringLiteral("wbLcsStartEdit"));
        wbLcsStartEdit->setGeometry(QRect(460, 370, 113, 27));
        wbLcsSuppressionEdit = new QLineEdit(WhiteBalance);
        wbLcsSuppressionEdit->setObjectName(QStringLiteral("wbLcsSuppressionEdit"));
        wbLcsSuppressionEdit->setGeometry(QRect(460, 420, 113, 27));
        wbSaturationEdit = new QLineEdit(WhiteBalance);
        wbSaturationEdit->setObjectName(QStringLiteral("wbSaturationEdit"));
        wbSaturationEdit->setGeometry(QRect(460, 220, 113, 27));
        wbRGain = new QLineEdit(WhiteBalance);
        wbRGain->setObjectName(QStringLiteral("wbRGain"));
        wbRGain->setEnabled(false);
        wbRGain->setGeometry(QRect(360, 40, 81, 27));
        wbGrGain = new QLineEdit(WhiteBalance);
        wbGrGain->setObjectName(QStringLiteral("wbGrGain"));
        wbGrGain->setEnabled(false);
        wbGrGain->setGeometry(QRect(360, 70, 81, 27));
        wbGbGain = new QLineEdit(WhiteBalance);
        wbGbGain->setObjectName(QStringLiteral("wbGbGain"));
        wbGbGain->setEnabled(false);
        wbGbGain->setGeometry(QRect(360, 100, 81, 27));
        wbBGain = new QLineEdit(WhiteBalance);
        wbBGain->setObjectName(QStringLiteral("wbBGain"));
        wbBGain->setEnabled(false);
        wbBGain->setGeometry(QRect(360, 130, 81, 27));
        wbHue = new QLineEdit(WhiteBalance);
        wbHue->setObjectName(QStringLiteral("wbHue"));
        wbHue->setEnabled(false);
        wbHue->setGeometry(QRect(360, 190, 81, 27));
        wbSaturation = new QLineEdit(WhiteBalance);
        wbSaturation->setObjectName(QStringLiteral("wbSaturation"));
        wbSaturation->setEnabled(false);
        wbSaturation->setGeometry(QRect(360, 220, 81, 27));
        tabWidget->addTab(WhiteBalance, QString());
        Y = new QWidget();
        Y->setObjectName(QStringLiteral("Y"));
        label0301 = new QLabel(Y);
        label0301->setObjectName(QStringLiteral("label0301"));
        label0301->setGeometry(QRect(40, 20, 121, 17));
        label0302 = new QLabel(Y);
        label0302->setObjectName(QStringLiteral("label0302"));
        label0302->setGeometry(QRect(40, 60, 121, 17));
        label0303 = new QLabel(Y);
        label0303->setObjectName(QStringLiteral("label0303"));
        label0303->setGeometry(QRect(40, 100, 121, 17));
        label0304 = new QLabel(Y);
        label0304->setObjectName(QStringLiteral("label0304"));
        label0304->setGeometry(QRect(40, 150, 121, 17));
        label0305 = new QLabel(Y);
        label0305->setObjectName(QStringLiteral("label0305"));
        label0305->setGeometry(QRect(40, 190, 111, 17));
        label0306 = new QLabel(Y);
        label0306->setObjectName(QStringLiteral("label0306"));
        label0306->setGeometry(QRect(40, 230, 131, 17));
        label0307 = new QLabel(Y);
        label0307->setObjectName(QStringLiteral("label0307"));
        label0307->setGeometry(QRect(40, 270, 101, 17));
        label0308 = new QLabel(Y);
        label0308->setObjectName(QStringLiteral("label0308"));
        label0308->setGeometry(QRect(40, 310, 141, 17));
        label0309 = new QLabel(Y);
        label0309->setObjectName(QStringLiteral("label0309"));
        label0309->setGeometry(QRect(40, 350, 231, 17));
        label0310 = new QLabel(Y);
        label0310->setObjectName(QStringLiteral("label0310"));
        label0310->setGeometry(QRect(40, 410, 181, 17));
        yGammaValueSlider = new QSlider(Y);
        yGammaValueSlider->setObjectName(QStringLiteral("yGammaValueSlider"));
        yGammaValueSlider->setGeometry(QRect(200, 60, 160, 29));
        yGammaValueSlider->setOrientation(Qt::Horizontal);
        yCameraGammaSlider = new QSlider(Y);
        yCameraGammaSlider->setObjectName(QStringLiteral("yCameraGammaSlider"));
        yCameraGammaSlider->setGeometry(QRect(200, 100, 160, 29));
        yCameraGammaSlider->setOrientation(Qt::Horizontal);
        ySharpnessgainSlider = new QSlider(Y);
        ySharpnessgainSlider->setObjectName(QStringLiteral("ySharpnessgainSlider"));
        ySharpnessgainSlider->setGeometry(QRect(200, 180, 160, 29));
        ySharpnessgainSlider->setOrientation(Qt::Horizontal);
        ySharpnessCoringSlider = new QSlider(Y);
        ySharpnessCoringSlider->setObjectName(QStringLiteral("ySharpnessCoringSlider"));
        ySharpnessCoringSlider->setGeometry(QRect(200, 220, 160, 29));
        ySharpnessCoringSlider->setOrientation(Qt::Horizontal);
        yDigitalClampSlider = new QSlider(Y);
        yDigitalClampSlider->setObjectName(QStringLiteral("yDigitalClampSlider"));
        yDigitalClampSlider->setGeometry(QRect(200, 260, 160, 29));
        yDigitalClampSlider->setOrientation(Qt::Horizontal);
        yAnalogBlackLevelSlider = new QSlider(Y);
        yAnalogBlackLevelSlider->setObjectName(QStringLiteral("yAnalogBlackLevelSlider"));
        yAnalogBlackLevelSlider->setGeometry(QRect(200, 300, 160, 29));
        yAnalogBlackLevelSlider->setOrientation(Qt::Horizontal);
        yShadingTargetSlider = new QSlider(Y);
        yShadingTargetSlider->setObjectName(QStringLiteral("yShadingTargetSlider"));
        yShadingTargetSlider->setGeometry(QRect(200, 370, 160, 29));
        yShadingTargetSlider->setOrientation(Qt::Horizontal);
        yGammaMode = new QComboBox(Y);
        yGammaMode->setObjectName(QStringLiteral("yGammaMode"));
        yGammaMode->setGeometry(QRect(204, 10, 151, 27));
        yShadingMode = new QComboBox(Y);
        yShadingMode->setObjectName(QStringLiteral("yShadingMode"));
        yShadingMode->setGeometry(QRect(200, 430, 161, 27));
        ySharpnessMode = new QComboBox(Y);
        ySharpnessMode->setObjectName(QStringLiteral("ySharpnessMode"));
        ySharpnessMode->setGeometry(QRect(200, 140, 161, 27));
        yGammaValue = new QLineEdit(Y);
        yGammaValue->setObjectName(QStringLiteral("yGammaValue"));
        yGammaValue->setEnabled(false);
        yGammaValue->setGeometry(QRect(420, 60, 113, 27));
        yCameraGamma = new QLineEdit(Y);
        yCameraGamma->setObjectName(QStringLiteral("yCameraGamma"));
        yCameraGamma->setEnabled(false);
        yCameraGamma->setGeometry(QRect(420, 100, 113, 27));
        ySharpnessgain = new QLineEdit(Y);
        ySharpnessgain->setObjectName(QStringLiteral("ySharpnessgain"));
        ySharpnessgain->setEnabled(false);
        ySharpnessgain->setGeometry(QRect(420, 180, 113, 27));
        ySharpnessCoring = new QLineEdit(Y);
        ySharpnessCoring->setObjectName(QStringLiteral("ySharpnessCoring"));
        ySharpnessCoring->setEnabled(false);
        ySharpnessCoring->setGeometry(QRect(420, 220, 113, 27));
        yDigitalClamp = new QLineEdit(Y);
        yDigitalClamp->setObjectName(QStringLiteral("yDigitalClamp"));
        yDigitalClamp->setEnabled(false);
        yDigitalClamp->setGeometry(QRect(420, 260, 113, 27));
        yAnalogBlackLevel = new QLineEdit(Y);
        yAnalogBlackLevel->setObjectName(QStringLiteral("yAnalogBlackLevel"));
        yAnalogBlackLevel->setEnabled(false);
        yAnalogBlackLevel->setGeometry(QRect(420, 300, 113, 27));
        yShadingTarget = new QLineEdit(Y);
        yShadingTarget->setObjectName(QStringLiteral("yShadingTarget"));
        yShadingTarget->setEnabled(false);
        yShadingTarget->setGeometry(QRect(420, 370, 113, 27));
        tabWidget->addTab(Y, QString());
        ColorGamma = new QWidget();
        ColorGamma->setObjectName(QStringLiteral("ColorGamma"));
        label0401 = new QLabel(ColorGamma);
        label0401->setObjectName(QStringLiteral("label0401"));
        label0401->setGeometry(QRect(40, 30, 131, 17));
        label0402 = new QLabel(ColorGamma);
        label0402->setObjectName(QStringLiteral("label0402"));
        label0402->setGeometry(QRect(40, 70, 121, 17));
        label0403 = new QLabel(ColorGamma);
        label0403->setObjectName(QStringLiteral("label0403"));
        label0403->setGeometry(QRect(40, 130, 131, 17));
        label0404 = new QLabel(ColorGamma);
        label0404->setObjectName(QStringLiteral("label0404"));
        label0404->setGeometry(QRect(40, 170, 131, 17));
        label0405 = new QLabel(ColorGamma);
        label0405->setObjectName(QStringLiteral("label0405"));
        label0405->setGeometry(QRect(40, 240, 131, 17));
        label0406 = new QLabel(ColorGamma);
        label0406->setObjectName(QStringLiteral("label0406"));
        label0406->setGeometry(QRect(40, 280, 121, 17));
        label0407 = new QLabel(ColorGamma);
        label0407->setObjectName(QStringLiteral("label0407"));
        label0407->setGeometry(QRect(40, 340, 121, 17));
        label0408 = new QLabel(ColorGamma);
        label0408->setObjectName(QStringLiteral("label0408"));
        label0408->setGeometry(QRect(40, 370, 121, 17));
        cgRGammaValueSlider = new QSlider(ColorGamma);
        cgRGammaValueSlider->setObjectName(QStringLiteral("cgRGammaValueSlider"));
        cgRGammaValueSlider->setGeometry(QRect(200, 70, 160, 29));
        cgRGammaValueSlider->setOrientation(Qt::Horizontal);
        cgGrGammaValueSlider = new QSlider(ColorGamma);
        cgGrGammaValueSlider->setObjectName(QStringLiteral("cgGrGammaValueSlider"));
        cgGrGammaValueSlider->setGeometry(QRect(200, 170, 160, 29));
        cgGrGammaValueSlider->setOrientation(Qt::Horizontal);
        cgGbGammaValueSlider = new QSlider(ColorGamma);
        cgGbGammaValueSlider->setObjectName(QStringLiteral("cgGbGammaValueSlider"));
        cgGbGammaValueSlider->setGeometry(QRect(200, 280, 160, 29));
        cgGbGammaValueSlider->setOrientation(Qt::Horizontal);
        cgBGammaValueSlider = new QSlider(ColorGamma);
        cgBGammaValueSlider->setObjectName(QStringLiteral("cgBGammaValueSlider"));
        cgBGammaValueSlider->setGeometry(QRect(200, 370, 160, 29));
        cgBGammaValueSlider->setOrientation(Qt::Horizontal);
        cgRGammaMode = new QComboBox(ColorGamma);
        cgRGammaMode->setObjectName(QStringLiteral("cgRGammaMode"));
        cgRGammaMode->setGeometry(QRect(224, 30, 141, 27));
        cgGrGammaMode = new QComboBox(ColorGamma);
        cgGrGammaMode->setObjectName(QStringLiteral("cgGrGammaMode"));
        cgGrGammaMode->setGeometry(QRect(220, 130, 141, 27));
        cgGbGammaMode = new QComboBox(ColorGamma);
        cgGbGammaMode->setObjectName(QStringLiteral("cgGbGammaMode"));
        cgGbGammaMode->setGeometry(QRect(224, 240, 141, 27));
        cgBGammaMode = new QComboBox(ColorGamma);
        cgBGammaMode->setObjectName(QStringLiteral("cgBGammaMode"));
        cgBGammaMode->setGeometry(QRect(220, 340, 141, 27));
        cgRGammaValue = new QLineEdit(ColorGamma);
        cgRGammaValue->setObjectName(QStringLiteral("cgRGammaValue"));
        cgRGammaValue->setEnabled(false);
        cgRGammaValue->setGeometry(QRect(420, 70, 113, 27));
        cgGrGammaValue = new QLineEdit(ColorGamma);
        cgGrGammaValue->setObjectName(QStringLiteral("cgGrGammaValue"));
        cgGrGammaValue->setEnabled(false);
        cgGrGammaValue->setGeometry(QRect(420, 170, 113, 27));
        cgGbGammaValue = new QLineEdit(ColorGamma);
        cgGbGammaValue->setObjectName(QStringLiteral("cgGbGammaValue"));
        cgGbGammaValue->setEnabled(false);
        cgGbGammaValue->setGeometry(QRect(420, 280, 113, 27));
        cgBGammaValue = new QLineEdit(ColorGamma);
        cgBGammaValue->setObjectName(QStringLiteral("cgBGammaValue"));
        cgBGammaValue->setEnabled(false);
        cgBGammaValue->setGeometry(QRect(420, 370, 113, 27));
        tabWidget->addTab(ColorGamma, QString());
        TriggerMode = new QWidget();
        TriggerMode->setObjectName(QStringLiteral("TriggerMode"));
        label0501 = new QLabel(TriggerMode);
        label0501->setObjectName(QStringLiteral("label0501"));
        label0501->setGeometry(QRect(40, 20, 111, 17));
        label0502 = new QLabel(TriggerMode);
        label0502->setObjectName(QStringLiteral("label0502"));
        label0502->setGeometry(QRect(40, 50, 111, 17));
        label0503 = new QLabel(TriggerMode);
        label0503->setObjectName(QStringLiteral("label0503"));
        label0503->setGeometry(QRect(40, 80, 111, 17));
        label0504 = new QLabel(TriggerMode);
        label0504->setObjectName(QStringLiteral("label0504"));
        label0504->setGeometry(QRect(40, 110, 111, 17));
        label0505 = new QLabel(TriggerMode);
        label0505->setObjectName(QStringLiteral("label0505"));
        label0505->setGeometry(QRect(40, 140, 101, 17));
        label0506 = new QLabel(TriggerMode);
        label0506->setObjectName(QStringLiteral("label0506"));
        label0506->setGeometry(QRect(40, 170, 121, 17));
        label0507 = new QLabel(TriggerMode);
        label0507->setObjectName(QStringLiteral("label0507"));
        label0507->setGeometry(QRect(10, 210, 121, 17));
        label0511 = new QLabel(TriggerMode);
        label0511->setObjectName(QStringLiteral("label0511"));
        label0511->setGeometry(QRect(40, 430, 161, 17));
        label0508 = new QLabel(TriggerMode);
        label0508->setObjectName(QStringLiteral("label0508"));
        label0508->setGeometry(QRect(40, 340, 121, 17));
        label0509 = new QLabel(TriggerMode);
        label0509->setObjectName(QStringLiteral("label0509"));
        label0509->setGeometry(QRect(40, 370, 67, 17));
        label0510 = new QLabel(TriggerMode);
        label0510->setObjectName(QStringLiteral("label0510"));
        label0510->setGeometry(QRect(40, 400, 121, 17));
        tmExposureMode = new QComboBox(TriggerMode);
        tmExposureMode->setObjectName(QStringLiteral("tmExposureMode"));
        tmExposureMode->setGeometry(QRect(170, 10, 211, 27));
        tmTriggerSelect = new QComboBox(TriggerMode);
        tmTriggerSelect->setObjectName(QStringLiteral("tmTriggerSelect"));
        tmTriggerSelect->setGeometry(QRect(170, 40, 211, 27));
        tmTriggerMode = new QComboBox(TriggerMode);
        tmTriggerMode->setObjectName(QStringLiteral("tmTriggerMode"));
        tmTriggerMode->setGeometry(QRect(170, 70, 211, 27));
        tmTriggerSource = new QComboBox(TriggerMode);
        tmTriggerSource->setObjectName(QStringLiteral("tmTriggerSource"));
        tmTriggerSource->setGeometry(QRect(170, 100, 211, 27));
        tmTriggerOverlap = new QComboBox(TriggerMode);
        tmTriggerOverlap->setObjectName(QStringLiteral("tmTriggerOverlap"));
        tmTriggerOverlap->setGeometry(QRect(170, 160, 211, 27));
        tmNoiseReduction = new QComboBox(TriggerMode);
        tmNoiseReduction->setObjectName(QStringLiteral("tmNoiseReduction"));
        tmNoiseReduction->setGeometry(QRect(204, 340, 181, 27));
        tmWaitHd = new QComboBox(TriggerMode);
        tmWaitHd->setObjectName(QStringLiteral("tmWaitHd"));
        tmWaitHd->setGeometry(QRect(204, 370, 181, 27));
        tmWaitReadOut = new QComboBox(TriggerMode);
        tmWaitReadOut->setObjectName(QStringLiteral("tmWaitReadOut"));
        tmWaitReadOut->setGeometry(QRect(204, 400, 181, 27));
        tmShutterMode = new QComboBox(TriggerMode);
        tmShutterMode->setObjectName(QStringLiteral("tmShutterMode"));
        tmShutterMode->setGeometry(QRect(204, 430, 181, 27));
        tmTriggerDelaySlider = new QSlider(TriggerMode);
        tmTriggerDelaySlider->setObjectName(QStringLiteral("tmTriggerDelaySlider"));
        tmTriggerDelaySlider->setGeometry(QRect(170, 130, 160, 29));
        tmTriggerDelaySlider->setOrientation(Qt::Horizontal);
        tmAutoExposureEndSlider = new QSlider(TriggerMode);
        tmAutoExposureEndSlider->setObjectName(QStringLiteral("tmAutoExposureEndSlider"));
        tmAutoExposureEndSlider->setGeometry(QRect(170, 290, 160, 29));
        tmAutoExposureEndSlider->setOrientation(Qt::Horizontal);
        tmTriggerDelayEdit = new QLineEdit(TriggerMode);
        tmTriggerDelayEdit->setObjectName(QStringLiteral("tmTriggerDelayEdit"));
        tmTriggerDelayEdit->setGeometry(QRect(450, 130, 113, 27));
        tmAutoExposureEndEdit = new QLineEdit(TriggerMode);
        tmAutoExposureEndEdit->setObjectName(QStringLiteral("tmAutoExposureEndEdit"));
        tmAutoExposureEndEdit->setGeometry(QRect(360, 290, 113, 27));
        tmFrameStart = new QPushButton(TriggerMode);
        tmFrameStart->setObjectName(QStringLiteral("tmFrameStart"));
        tmFrameStart->setGeometry(QRect(40, 230, 131, 27));
        tmExposureStart = new QPushButton(TriggerMode);
        tmExposureStart->setObjectName(QStringLiteral("tmExposureStart"));
        tmExposureStart->setGeometry(QRect(170, 230, 131, 27));
        tmExposureEnd = new QPushButton(TriggerMode);
        tmExposureEnd->setObjectName(QStringLiteral("tmExposureEnd"));
        tmExposureEnd->setGeometry(QRect(300, 230, 131, 27));
        tmReadOut = new QPushButton(TriggerMode);
        tmReadOut->setObjectName(QStringLiteral("tmReadOut"));
        tmReadOut->setGeometry(QRect(430, 230, 131, 27));
        tmAutoExposureEndCheck = new QCheckBox(TriggerMode);
        tmAutoExposureEndCheck->setObjectName(QStringLiteral("tmAutoExposureEndCheck"));
        tmAutoExposureEndCheck->setGeometry(QRect(40, 270, 211, 22));
        tmTriggerDelay = new QLineEdit(TriggerMode);
        tmTriggerDelay->setObjectName(QStringLiteral("tmTriggerDelay"));
        tmTriggerDelay->setEnabled(false);
        tmTriggerDelay->setGeometry(QRect(350, 130, 91, 27));
        tabWidget->addTab(TriggerMode, QString());
        TriggerTiming = new QWidget();
        TriggerTiming->setObjectName(QStringLiteral("TriggerTiming"));
        label0601 = new QLabel(TriggerTiming);
        label0601->setObjectName(QStringLiteral("label0601"));
        label0601->setGeometry(QRect(20, 30, 141, 17));
        ttStrobeStartSlider = new QSlider(TriggerTiming);
        ttStrobeStartSlider->setObjectName(QStringLiteral("ttStrobeStartSlider"));
        ttStrobeStartSlider->setGeometry(QRect(180, 30, 160, 29));
        ttStrobeStartSlider->setOrientation(Qt::Horizontal);
        ttStrobeStartEdit = new QLineEdit(TriggerTiming);
        ttStrobeStartEdit->setObjectName(QStringLiteral("ttStrobeStartEdit"));
        ttStrobeStartEdit->setGeometry(QRect(450, 30, 113, 27));
        label0602 = new QLabel(TriggerTiming);
        label0602->setObjectName(QStringLiteral("label0602"));
        label0602->setGeometry(QRect(20, 80, 121, 17));
        label0603 = new QLabel(TriggerTiming);
        label0603->setObjectName(QStringLiteral("label0603"));
        label0603->setGeometry(QRect(20, 130, 141, 17));
        label0604 = new QLabel(TriggerTiming);
        label0604->setObjectName(QStringLiteral("label0604"));
        label0604->setGeometry(QRect(20, 180, 161, 17));
        label0605 = new QLabel(TriggerTiming);
        label0605->setObjectName(QStringLiteral("label0605"));
        label0605->setGeometry(QRect(20, 230, 111, 17));
        label0606 = new QLabel(TriggerTiming);
        label0606->setObjectName(QStringLiteral("label0606"));
        label0606->setGeometry(QRect(20, 280, 151, 17));
        ttStrobeEndSlider = new QSlider(TriggerTiming);
        ttStrobeEndSlider->setObjectName(QStringLiteral("ttStrobeEndSlider"));
        ttStrobeEndSlider->setGeometry(QRect(180, 70, 160, 29));
        ttStrobeEndSlider->setOrientation(Qt::Horizontal);
        ttPulseDelaySlider = new QSlider(TriggerTiming);
        ttPulseDelaySlider->setObjectName(QStringLiteral("ttPulseDelaySlider"));
        ttPulseDelaySlider->setGeometry(QRect(180, 120, 160, 29));
        ttPulseDelaySlider->setOrientation(Qt::Horizontal);
        ttPulseDurationSlider = new QSlider(TriggerTiming);
        ttPulseDurationSlider->setObjectName(QStringLiteral("ttPulseDurationSlider"));
        ttPulseDurationSlider->setGeometry(QRect(180, 180, 160, 29));
        ttPulseDurationSlider->setOrientation(Qt::Horizontal);
        ttReadOutSlider = new QSlider(TriggerTiming);
        ttReadOutSlider->setObjectName(QStringLiteral("ttReadOutSlider"));
        ttReadOutSlider->setGeometry(QRect(180, 220, 160, 29));
        ttReadOutSlider->setOrientation(Qt::Horizontal);
        ttLineDebounceSlider = new QSlider(TriggerTiming);
        ttLineDebounceSlider->setObjectName(QStringLiteral("ttLineDebounceSlider"));
        ttLineDebounceSlider->setGeometry(QRect(180, 270, 160, 29));
        ttLineDebounceSlider->setOrientation(Qt::Horizontal);
        ttStrobeEndEdit = new QLineEdit(TriggerTiming);
        ttStrobeEndEdit->setObjectName(QStringLiteral("ttStrobeEndEdit"));
        ttStrobeEndEdit->setGeometry(QRect(450, 70, 113, 27));
        ttPulseDelayEdit = new QLineEdit(TriggerTiming);
        ttPulseDelayEdit->setObjectName(QStringLiteral("ttPulseDelayEdit"));
        ttPulseDelayEdit->setGeometry(QRect(450, 120, 113, 27));
        ttPulseDurationEdit = new QLineEdit(TriggerTiming);
        ttPulseDurationEdit->setObjectName(QStringLiteral("ttPulseDurationEdit"));
        ttPulseDurationEdit->setGeometry(QRect(450, 180, 113, 27));
        ttReadOutEdit = new QLineEdit(TriggerTiming);
        ttReadOutEdit->setObjectName(QStringLiteral("ttReadOutEdit"));
        ttReadOutEdit->setGeometry(QRect(450, 220, 113, 27));
        ttLineDebounceEdit = new QLineEdit(TriggerTiming);
        ttLineDebounceEdit->setObjectName(QStringLiteral("ttLineDebounceEdit"));
        ttLineDebounceEdit->setGeometry(QRect(450, 270, 113, 27));
        ttStrobeStart = new QLineEdit(TriggerTiming);
        ttStrobeStart->setObjectName(QStringLiteral("ttStrobeStart"));
        ttStrobeStart->setEnabled(false);
        ttStrobeStart->setGeometry(QRect(350, 30, 91, 27));
        ttStrobeEnd = new QLineEdit(TriggerTiming);
        ttStrobeEnd->setObjectName(QStringLiteral("ttStrobeEnd"));
        ttStrobeEnd->setEnabled(false);
        ttStrobeEnd->setGeometry(QRect(350, 70, 91, 27));
        ttPulseDelay = new QLineEdit(TriggerTiming);
        ttPulseDelay->setObjectName(QStringLiteral("ttPulseDelay"));
        ttPulseDelay->setEnabled(false);
        ttPulseDelay->setGeometry(QRect(350, 120, 91, 27));
        ttPulseDuration = new QLineEdit(TriggerTiming);
        ttPulseDuration->setObjectName(QStringLiteral("ttPulseDuration"));
        ttPulseDuration->setEnabled(false);
        ttPulseDuration->setGeometry(QRect(350, 180, 91, 27));
        ttReadOut = new QLineEdit(TriggerTiming);
        ttReadOut->setObjectName(QStringLiteral("ttReadOut"));
        ttReadOut->setEnabled(false);
        ttReadOut->setGeometry(QRect(350, 220, 91, 27));
        ttLineDebounce = new QLineEdit(TriggerTiming);
        ttLineDebounce->setObjectName(QStringLiteral("ttLineDebounce"));
        ttLineDebounce->setEnabled(false);
        ttLineDebounce->setGeometry(QRect(350, 270, 91, 27));
        tabWidget->addTab(TriggerTiming, QString());
        IO = new QWidget();
        IO->setObjectName(QStringLiteral("IO"));
        label0701 = new QLabel(IO);
        label0701->setObjectName(QStringLiteral("label0701"));
        label0701->setGeometry(QRect(20, 40, 67, 17));
        label0702 = new QLabel(IO);
        label0702->setObjectName(QStringLiteral("label0702"));
        label0702->setGeometry(QRect(20, 70, 67, 17));
        label0703 = new QLabel(IO);
        label0703->setObjectName(QStringLiteral("label0703"));
        label0703->setGeometry(QRect(20, 100, 67, 17));
        label0709 = new QLabel(IO);
        label0709->setObjectName(QStringLiteral("label0709"));
        label0709->setGeometry(QRect(20, 180, 101, 17));
        label0705 = new QLabel(IO);
        label0705->setObjectName(QStringLiteral("label0705"));
        label0705->setGeometry(QRect(80, 10, 67, 17));
        label0706 = new QLabel(IO);
        label0706->setObjectName(QStringLiteral("label0706"));
        label0706->setGeometry(QRect(180, 10, 67, 17));
        label0707 = new QLabel(IO);
        label0707->setObjectName(QStringLiteral("label0707"));
        label0707->setGeometry(QRect(390, 10, 81, 17));
        label0708 = new QLabel(IO);
        label0708->setObjectName(QStringLiteral("label0708"));
        label0708->setGeometry(QRect(490, 10, 67, 17));
        label0704 = new QLabel(IO);
        label0704->setObjectName(QStringLiteral("label0704"));
        label0704->setGeometry(QRect(20, 130, 67, 17));
        label0710 = new QLabel(IO);
        label0710->setObjectName(QStringLiteral("label0710"));
        label0710->setGeometry(QRect(20, 220, 67, 17));
        label0711 = new QLabel(IO);
        label0711->setObjectName(QStringLiteral("label0711"));
        label0711->setGeometry(QRect(20, 270, 41, 17));
        io0InOut = new QComboBox(IO);
        io0InOut->setObjectName(QStringLiteral("io0InOut"));
        io0InOut->setGeometry(QRect(80, 40, 91, 27));
        io1InOut = new QComboBox(IO);
        io1InOut->setObjectName(QStringLiteral("io1InOut"));
        io1InOut->setGeometry(QRect(80, 70, 91, 27));
        io3Status = new QComboBox(IO);
        io3Status->setObjectName(QStringLiteral("io3Status"));
        io3Status->setGeometry(QRect(480, 130, 85, 27));
        io3NegaPosi = new QComboBox(IO);
        io3NegaPosi->setObjectName(QStringLiteral("io3NegaPosi"));
        io3NegaPosi->setGeometry(QRect(390, 130, 91, 27));
        io2Mode = new QComboBox(IO);
        io2Mode->setObjectName(QStringLiteral("io2Mode"));
        io2Mode->setGeometry(QRect(170, 100, 221, 27));
        io2InOut = new QComboBox(IO);
        io2InOut->setObjectName(QStringLiteral("io2InOut"));
        io2InOut->setGeometry(QRect(80, 100, 91, 27));
        io2Status = new QComboBox(IO);
        io2Status->setObjectName(QStringLiteral("io2Status"));
        io2Status->setGeometry(QRect(480, 100, 85, 27));
        io2NegaPosi = new QComboBox(IO);
        io2NegaPosi->setObjectName(QStringLiteral("io2NegaPosi"));
        io2NegaPosi->setGeometry(QRect(390, 100, 91, 27));
        io0Status = new QComboBox(IO);
        io0Status->setObjectName(QStringLiteral("io0Status"));
        io0Status->setGeometry(QRect(480, 40, 85, 27));
        io3Mode = new QComboBox(IO);
        io3Mode->setObjectName(QStringLiteral("io3Mode"));
        io3Mode->setGeometry(QRect(170, 130, 221, 27));
        io1Mode = new QComboBox(IO);
        io1Mode->setObjectName(QStringLiteral("io1Mode"));
        io1Mode->setGeometry(QRect(170, 70, 221, 27));
        io1Status = new QComboBox(IO);
        io1Status->setObjectName(QStringLiteral("io1Status"));
        io1Status->setGeometry(QRect(480, 70, 85, 27));
        io0NegaPosi = new QComboBox(IO);
        io0NegaPosi->setObjectName(QStringLiteral("io0NegaPosi"));
        io0NegaPosi->setGeometry(QRect(390, 40, 91, 27));
        io0Mode = new QComboBox(IO);
        io0Mode->setObjectName(QStringLiteral("io0Mode"));
        io0Mode->setGeometry(QRect(170, 40, 221, 27));
        io1NegaPosi = new QComboBox(IO);
        io1NegaPosi->setObjectName(QStringLiteral("io1NegaPosi"));
        io1NegaPosi->setGeometry(QRect(390, 70, 91, 27));
        io3InOut = new QComboBox(IO);
        io3InOut->setObjectName(QStringLiteral("io3InOut"));
        io3InOut->setGeometry(QRect(80, 130, 91, 27));
        ioResetSwitch = new QComboBox(IO);
        ioResetSwitch->setObjectName(QStringLiteral("ioResetSwitch"));
        ioResetSwitch->setGeometry(QRect(120, 170, 151, 27));
        ioLed = new QComboBox(IO);
        ioLed->setObjectName(QStringLiteral("ioLed"));
        ioLed->setGeometry(QRect(80, 260, 151, 27));
        label0714 = new QLabel(IO);
        label0714->setObjectName(QStringLiteral("label0714"));
        label0714->setGeometry(QRect(20, 320, 101, 17));
        ioSw0 = new QLineEdit(IO);
        ioSw0->setObjectName(QStringLiteral("ioSw0"));
        ioSw0->setEnabled(false);
        ioSw0->setGeometry(QRect(80, 210, 61, 27));
        ioSw1 = new QLineEdit(IO);
        ioSw1->setObjectName(QStringLiteral("ioSw1"));
        ioSw1->setEnabled(false);
        ioSw1->setGeometry(QRect(150, 210, 61, 27));
        ioSw2 = new QLineEdit(IO);
        ioSw2->setObjectName(QStringLiteral("ioSw2"));
        ioSw2->setEnabled(false);
        ioSw2->setGeometry(QRect(220, 210, 61, 27));
        ioSw3 = new QLineEdit(IO);
        ioSw3->setObjectName(QStringLiteral("ioSw3"));
        ioSw3->setEnabled(false);
        ioSw3->setGeometry(QRect(290, 210, 61, 27));
        ioTemperature = new QLineEdit(IO);
        ioTemperature->setObjectName(QStringLiteral("ioTemperature"));
        ioTemperature->setEnabled(false);
        ioTemperature->setGeometry(QRect(140, 310, 91, 27));
        ioResetCounter = new QPushButton(IO);
        ioResetCounter->setObjectName(QStringLiteral("ioResetCounter"));
        ioResetCounter->setGeometry(QRect(40, 420, 161, 27));
        ioClearBuffer = new QPushButton(IO);
        ioClearBuffer->setObjectName(QStringLiteral("ioClearBuffer"));
        ioClearBuffer->setGeometry(QRect(220, 420, 161, 27));
        tabWidget->addTab(IO, QString());
        HDR = new QWidget();
        HDR->setObjectName(QStringLiteral("HDR"));
        label0801 = new QLabel(HDR);
        label0801->setObjectName(QStringLiteral("label0801"));
        label0801->setGeometry(QRect(40, 40, 91, 17));
        label0802 = new QLabel(HDR);
        label0802->setObjectName(QStringLiteral("label0802"));
        label0802->setGeometry(QRect(40, 90, 121, 17));
        label0803 = new QLabel(HDR);
        label0803->setObjectName(QStringLiteral("label0803"));
        label0803->setGeometry(QRect(40, 150, 67, 17));
        label0804 = new QLabel(HDR);
        label0804->setObjectName(QStringLiteral("label0804"));
        label0804->setGeometry(QRect(40, 200, 67, 17));
        label0805 = new QLabel(HDR);
        label0805->setObjectName(QStringLiteral("label0805"));
        label0805->setGeometry(QRect(40, 260, 67, 17));
        label0806 = new QLabel(HDR);
        label0806->setObjectName(QStringLiteral("label0806"));
        label0806->setGeometry(QRect(40, 320, 67, 17));
        hdrMode = new QComboBox(HDR);
        hdrMode->setObjectName(QStringLiteral("hdrMode"));
        hdrMode->setGeometry(QRect(214, 30, 131, 27));
        hdrSlope = new QComboBox(HDR);
        hdrSlope->setObjectName(QStringLiteral("hdrSlope"));
        hdrSlope->setGeometry(QRect(214, 80, 131, 27));
        hdrKnee1Slider = new QSlider(HDR);
        hdrKnee1Slider->setObjectName(QStringLiteral("hdrKnee1Slider"));
        hdrKnee1Slider->setGeometry(QRect(180, 150, 160, 29));
        hdrKnee1Slider->setOrientation(Qt::Horizontal);
        hdrVlow2Slider = new QSlider(HDR);
        hdrVlow2Slider->setObjectName(QStringLiteral("hdrVlow2Slider"));
        hdrVlow2Slider->setGeometry(QRect(180, 200, 160, 29));
        hdrVlow2Slider->setOrientation(Qt::Horizontal);
        hdrKnee2Slider = new QSlider(HDR);
        hdrKnee2Slider->setObjectName(QStringLiteral("hdrKnee2Slider"));
        hdrKnee2Slider->setGeometry(QRect(180, 250, 160, 29));
        hdrKnee2Slider->setOrientation(Qt::Horizontal);
        hdrVlow3Slider = new QSlider(HDR);
        hdrVlow3Slider->setObjectName(QStringLiteral("hdrVlow3Slider"));
        hdrVlow3Slider->setGeometry(QRect(180, 310, 160, 29));
        hdrVlow3Slider->setOrientation(Qt::Horizontal);
        hdrKnee1Edit = new QLineEdit(HDR);
        hdrKnee1Edit->setObjectName(QStringLiteral("hdrKnee1Edit"));
        hdrKnee1Edit->setGeometry(QRect(430, 150, 113, 27));
        hdrVlow2Edit = new QLineEdit(HDR);
        hdrVlow2Edit->setObjectName(QStringLiteral("hdrVlow2Edit"));
        hdrVlow2Edit->setGeometry(QRect(430, 200, 113, 27));
        hdrKnee2Edit = new QLineEdit(HDR);
        hdrKnee2Edit->setObjectName(QStringLiteral("hdrKnee2Edit"));
        hdrKnee2Edit->setGeometry(QRect(430, 250, 113, 27));
        hdrVlow3Edit = new QLineEdit(HDR);
        hdrVlow3Edit->setObjectName(QStringLiteral("hdrVlow3Edit"));
        hdrVlow3Edit->setGeometry(QRect(430, 310, 113, 27));
        tabWidget->addTab(HDR, QString());
        EEPROM = new QWidget();
        EEPROM->setObjectName(QStringLiteral("EEPROM"));
        eepLoadStandard = new QPushButton(EEPROM);
        eepLoadStandard->setObjectName(QStringLiteral("eepLoadStandard"));
        eepLoadStandard->setGeometry(QRect(50, 30, 231, 27));
        eepSaveStandard = new QPushButton(EEPROM);
        eepSaveStandard->setObjectName(QStringLiteral("eepSaveStandard"));
        eepSaveStandard->setGeometry(QRect(50, 80, 231, 27));
        eepReset = new QPushButton(EEPROM);
        eepReset->setObjectName(QStringLiteral("eepReset"));
        eepReset->setGeometry(QRect(50, 130, 231, 27));
        eepLoadDpp = new QPushButton(EEPROM);
        eepLoadDpp->setObjectName(QStringLiteral("eepLoadDpp"));
        eepLoadDpp->setGeometry(QRect(50, 190, 231, 27));
        eepSaveDpp = new QPushButton(EEPROM);
        eepSaveDpp->setObjectName(QStringLiteral("eepSaveDpp"));
        eepSaveDpp->setGeometry(QRect(50, 250, 231, 27));
        tabWidget->addTab(EEPROM, QString());
        Other = new QWidget();
        Other->setObjectName(QStringLiteral("Other"));
        label1001 = new QLabel(Other);
        label1001->setObjectName(QStringLiteral("label1001"));
        label1001->setGeometry(QRect(30, 10, 91, 17));
        label1002 = new QLabel(Other);
        label1002->setObjectName(QStringLiteral("label1002"));
        label1002->setGeometry(QRect(30, 40, 161, 17));
        label1004 = new QLabel(Other);
        label1004->setObjectName(QStringLiteral("label1004"));
        label1004->setGeometry(QRect(30, 70, 121, 17));
        label1005 = new QLabel(Other);
        label1005->setObjectName(QStringLiteral("label1005"));
        label1005->setGeometry(QRect(30, 100, 71, 17));
        label1007 = new QLabel(Other);
        label1007->setObjectName(QStringLiteral("label1007"));
        label1007->setGeometry(QRect(30, 140, 67, 17));
        label1008 = new QLabel(Other);
        label1008->setObjectName(QStringLiteral("label1008"));
        label1008->setGeometry(QRect(30, 170, 67, 17));
        label1009 = new QLabel(Other);
        label1009->setObjectName(QStringLiteral("label1009"));
        label1009->setGeometry(QRect(30, 200, 67, 17));
        label1010 = new QLabel(Other);
        label1010->setObjectName(QStringLiteral("label1010"));
        label1010->setGeometry(QRect(30, 230, 67, 17));
        label1012 = new QLabel(Other);
        label1012->setObjectName(QStringLiteral("label1012"));
        label1012->setGeometry(QRect(30, 290, 67, 17));
        label1011 = new QLabel(Other);
        label1011->setObjectName(QStringLiteral("label1011"));
        label1011->setGeometry(QRect(30, 260, 121, 17));
        label1013 = new QLabel(Other);
        label1013->setObjectName(QStringLiteral("label1013"));
        label1013->setGeometry(QRect(30, 330, 101, 17));
        label1014 = new QLabel(Other);
        label1014->setObjectName(QStringLiteral("label1014"));
        label1014->setGeometry(QRect(30, 360, 151, 17));
        label1015 = new QLabel(Other);
        label1015->setObjectName(QStringLiteral("label1015"));
        label1015->setGeometry(QRect(30, 390, 141, 17));
        label1016 = new QLabel(Other);
        label1016->setObjectName(QStringLiteral("label1016"));
        label1016->setGeometry(QRect(30, 420, 101, 17));
        label1017 = new QLabel(Other);
        label1017->setObjectName(QStringLiteral("label1017"));
        label1017->setGeometry(QRect(30, 450, 111, 17));
        label1006 = new QLabel(Other);
        label1006->setObjectName(QStringLiteral("label1006"));
        label1006->setGeometry(QRect(310, 100, 101, 17));
        otScanMode = new QComboBox(Other);
        otScanMode->setObjectName(QStringLiteral("otScanMode"));
        otScanMode->setGeometry(QRect(190, 10, 251, 27));
        otBinSum = new QComboBox(Other);
        otBinSum->setObjectName(QStringLiteral("otBinSum"));
        otBinSum->setGeometry(QRect(190, 70, 85, 27));
        otRegion = new QComboBox(Other);
        otRegion->setObjectName(QStringLiteral("otRegion"));
        otRegion->setGeometry(QRect(190, 100, 85, 27));
        otRegionMode = new QComboBox(Other);
        otRegionMode->setObjectName(QStringLiteral("otRegionMode"));
        otRegionMode->setGeometry(QRect(470, 100, 85, 27));
        otTransferBits = new QComboBox(Other);
        otTransferBits->setObjectName(QStringLiteral("otTransferBits"));
        otTransferBits->setGeometry(QRect(194, 330, 161, 27));
        otDisplayPixFormat = new QComboBox(Other);
        otDisplayPixFormat->setObjectName(QStringLiteral("otDisplayPixFormat"));
        otDisplayPixFormat->setGeometry(QRect(194, 360, 161, 27));
        otColorInterpolation = new QComboBox(Other);
        otColorInterpolation->setObjectName(QStringLiteral("otColorInterpolation"));
        otColorInterpolation->setGeometry(QRect(194, 390, 161, 27));
        otRotationMode = new QComboBox(Other);
        otRotationMode->setObjectName(QStringLiteral("otRotationMode"));
        otRotationMode->setGeometry(QRect(194, 450, 161, 27));
        otClock = new QComboBox(Other);
        otClock->setObjectName(QStringLiteral("otClock"));
        otClock->setGeometry(QRect(190, 290, 161, 27));
        otOffsetXSlider = new QSlider(Other);
        otOffsetXSlider->setObjectName(QStringLiteral("otOffsetXSlider"));
        otOffsetXSlider->setGeometry(QRect(190, 140, 160, 29));
        otOffsetXSlider->setSingleStep(1);
        otOffsetXSlider->setOrientation(Qt::Horizontal);
        otWidthSlider = new QSlider(Other);
        otWidthSlider->setObjectName(QStringLiteral("otWidthSlider"));
        otWidthSlider->setGeometry(QRect(190, 200, 160, 29));
        otWidthSlider->setSingleStep(1);
        otWidthSlider->setOrientation(Qt::Horizontal);
        otOffsetYSlider = new QSlider(Other);
        otOffsetYSlider->setObjectName(QStringLiteral("otOffsetYSlider"));
        otOffsetYSlider->setGeometry(QRect(190, 170, 160, 29));
        otOffsetYSlider->setSingleStep(1);
        otOffsetYSlider->setOrientation(Qt::Horizontal);
        otHeightSlider = new QSlider(Other);
        otHeightSlider->setObjectName(QStringLiteral("otHeightSlider"));
        otHeightSlider->setGeometry(QRect(190, 230, 160, 29));
        otHeightSlider->setSingleStep(1);
        otHeightSlider->setOrientation(Qt::Horizontal);
        otVBlankSlider = new QSlider(Other);
        otVBlankSlider->setObjectName(QStringLiteral("otVBlankSlider"));
        otVBlankSlider->setGeometry(QRect(190, 260, 160, 29));
        otVBlankSlider->setOrientation(Qt::Horizontal);
        otOffsetXEdit = new QLineEdit(Other);
        otOffsetXEdit->setObjectName(QStringLiteral("otOffsetXEdit"));
        otOffsetXEdit->setGeometry(QRect(440, 140, 113, 27));
        otWidthEdit = new QLineEdit(Other);
        otWidthEdit->setObjectName(QStringLiteral("otWidthEdit"));
        otWidthEdit->setGeometry(QRect(440, 200, 113, 27));
        otOffsetYEdit = new QLineEdit(Other);
        otOffsetYEdit->setObjectName(QStringLiteral("otOffsetYEdit"));
        otOffsetYEdit->setGeometry(QRect(440, 170, 113, 27));
        otHeightEdit = new QLineEdit(Other);
        otHeightEdit->setObjectName(QStringLiteral("otHeightEdit"));
        otHeightEdit->setGeometry(QRect(440, 230, 113, 27));
        otVBlankEdit = new QLineEdit(Other);
        otVBlankEdit->setObjectName(QStringLiteral("otVBlankEdit"));
        otVBlankEdit->setGeometry(QRect(440, 260, 113, 27));
        label1003 = new QLabel(Other);
        label1003->setObjectName(QStringLiteral("label1003"));
        label1003->setGeometry(QRect(310, 40, 161, 17));
        otMirrorMode = new QComboBox(Other);
        otMirrorMode->setObjectName(QStringLiteral("otMirrorMode"));
        otMirrorMode->setGeometry(QRect(194, 420, 161, 27));
        otFps = new QLineEdit(Other);
        otFps->setObjectName(QStringLiteral("otFps"));
        otFps->setEnabled(false);
        otFps->setGeometry(QRect(460, 300, 91, 27));
        label1017_2 = new QLabel(Other);
        label1017_2->setObjectName(QStringLiteral("label1017_2"));
        label1017_2->setGeometry(QRect(420, 300, 41, 17));
        otHDeciBin = new QComboBox(Other);
        otHDeciBin->setObjectName(QStringLiteral("otHDeciBin"));
        otHDeciBin->setGeometry(QRect(190, 40, 85, 27));
        otVDeciBin = new QComboBox(Other);
        otVDeciBin->setObjectName(QStringLiteral("otVDeciBin"));
        otVDeciBin->setGeometry(QRect(470, 40, 85, 27));
        tabWidget->addTab(Other, QString());
        label0001 = new QLabel(centralWidget);
        label0001->setObjectName(QStringLiteral("label0001"));
        label0001->setEnabled(true);
        label0001->setGeometry(QRect(20, 60, 91, 17));
        label0002 = new QLabel(centralWidget);
        label0002->setObjectName(QStringLiteral("label0002"));
        label0002->setGeometry(QRect(20, 120, 101, 17));
        label0003 = new QLabel(centralWidget);
        label0003->setObjectName(QStringLiteral("label0003"));
        label0003->setGeometry(QRect(20, 180, 91, 17));
        label0004 = new QLabel(centralWidget);
        label0004->setObjectName(QStringLiteral("label0004"));
        label0004->setGeometry(QRect(20, 240, 101, 17));
        label0005 = new QLabel(centralWidget);
        label0005->setObjectName(QStringLiteral("label0005"));
        label0005->setGeometry(QRect(20, 300, 111, 17));
        mainCamera = new QLineEdit(centralWidget);
        mainCamera->setObjectName(QStringLiteral("mainCamera"));
        mainCamera->setEnabled(false);
        mainCamera->setGeometry(QRect(10, 80, 151, 27));
        mainFpga = new QLineEdit(centralWidget);
        mainFpga->setObjectName(QStringLiteral("mainFpga"));
        mainFpga->setEnabled(false);
        mainFpga->setGeometry(QRect(10, 140, 151, 27));
        mainFirm = new QLineEdit(centralWidget);
        mainFirm->setObjectName(QStringLiteral("mainFirm"));
        mainFirm->setEnabled(false);
        mainFirm->setGeometry(QRect(10, 200, 151, 27));
        mainDriver = new QLineEdit(centralWidget);
        mainDriver->setObjectName(QStringLiteral("mainDriver"));
        mainDriver->setEnabled(false);
        mainDriver->setGeometry(QRect(10, 260, 151, 27));
        mainLibrary = new QLineEdit(centralWidget);
        mainLibrary->setObjectName(QStringLiteral("mainLibrary"));
        mainLibrary->setEnabled(false);
        mainLibrary->setGeometry(QRect(10, 320, 151, 27));
        mainCameraId = new QPushButton(centralWidget);
        mainCameraId->setObjectName(QStringLiteral("mainCameraId"));
        mainCameraId->setGeometry(QRect(30, 370, 99, 27));
        mainSettingFile = new QPushButton(centralWidget);
        mainSettingFile->setObjectName(QStringLiteral("mainSettingFile"));
        mainSettingFile->setGeometry(QRect(30, 420, 99, 27));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 766, 25));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Sentech USB Camera", Q_NULLPTR));
        mainCapture->setText(QApplication::translate("MainWindow", "Capture", Q_NULLPTR));
        label0101->setText(QApplication::translate("MainWindow", "Exposure", Q_NULLPTR));
        label0102->setText(QApplication::translate("MainWindow", "Analog Gain", Q_NULLPTR));
        label0103->setText(QApplication::translate("MainWindow", "Digital Gain", Q_NULLPTR));
        label0104->setText(QApplication::translate("MainWindow", "ALC Mode", Q_NULLPTR));
        label0105->setText(QApplication::translate("MainWindow", "ALC Target", Q_NULLPTR));
        label0106->setText(QApplication::translate("MainWindow", "AE Min Exposure", Q_NULLPTR));
        label0107->setText(QApplication::translate("MainWindow", "AE Max Exposure", Q_NULLPTR));
        label0108->setText(QApplication::translate("MainWindow", "AGC Min Gain", Q_NULLPTR));
        label0109->setText(QApplication::translate("MainWindow", "AGC Max Gain", Q_NULLPTR));
        label0110->setText(QApplication::translate("MainWindow", "Adjustment Digital Gain", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(ShutterGain), QApplication::translate("MainWindow", "ShutterGain", Q_NULLPTR));
        label0201->setText(QApplication::translate("MainWindow", "WB Mode", Q_NULLPTR));
        label0202->setText(QApplication::translate("MainWindow", "R Gain", Q_NULLPTR));
        label0203->setText(QApplication::translate("MainWindow", "Gr Gain", Q_NULLPTR));
        label0204->setText(QApplication::translate("MainWindow", "Gb Gain", Q_NULLPTR));
        label0205->setText(QApplication::translate("MainWindow", "B Gain", Q_NULLPTR));
        label0206->setText(QApplication::translate("MainWindow", "Hue/Saturation Mode", Q_NULLPTR));
        label0207->setText(QApplication::translate("MainWindow", "Hue", Q_NULLPTR));
        label0208->setText(QApplication::translate("MainWindow", "Saturation", Q_NULLPTR));
        label0209->setText(QApplication::translate("MainWindow", "High Chroma Suppression Start Level", Q_NULLPTR));
        label0211->setText(QApplication::translate("MainWindow", "Low Chroma Suppression Start Level", Q_NULLPTR));
        label0210->setText(QApplication::translate("MainWindow", "High Chroma Suppression Suppression Level", Q_NULLPTR));
        label0212->setText(QApplication::translate("MainWindow", "Low Chroma Suppression Suppression Level", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(WhiteBalance), QApplication::translate("MainWindow", "WhiteBalance", Q_NULLPTR));
        label0301->setText(QApplication::translate("MainWindow", "Y Gamma Mode", Q_NULLPTR));
        label0302->setText(QApplication::translate("MainWindow", "Y Gamma Value", Q_NULLPTR));
        label0303->setText(QApplication::translate("MainWindow", "Camera Gamma", Q_NULLPTR));
        label0304->setText(QApplication::translate("MainWindow", "Sharpness Mode", Q_NULLPTR));
        label0305->setText(QApplication::translate("MainWindow", "Sharpness Gain", Q_NULLPTR));
        label0306->setText(QApplication::translate("MainWindow", "Sharpness Coring", Q_NULLPTR));
        label0307->setText(QApplication::translate("MainWindow", "Digital Clamp", Q_NULLPTR));
        label0308->setText(QApplication::translate("MainWindow", "Analog Black Level", Q_NULLPTR));
        label0309->setText(QApplication::translate("MainWindow", "Shading Correction Target Level", Q_NULLPTR));
        label0310->setText(QApplication::translate("MainWindow", "Shading Correction Mode", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(Y), QApplication::translate("MainWindow", "Y", Q_NULLPTR));
        label0401->setText(QApplication::translate("MainWindow", "R Gamma Mode", Q_NULLPTR));
        label0402->setText(QApplication::translate("MainWindow", "R Gamma Value", Q_NULLPTR));
        label0403->setText(QApplication::translate("MainWindow", "GR Gamma Mode", Q_NULLPTR));
        label0404->setText(QApplication::translate("MainWindow", "GR Gamma Value", Q_NULLPTR));
        label0405->setText(QApplication::translate("MainWindow", "GB Gamma Mode", Q_NULLPTR));
        label0406->setText(QApplication::translate("MainWindow", "GB Gamma Value", Q_NULLPTR));
        label0407->setText(QApplication::translate("MainWindow", "B Gamma Mode", Q_NULLPTR));
        label0408->setText(QApplication::translate("MainWindow", "B Gamma Value", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(ColorGamma), QApplication::translate("MainWindow", "ColorGamma", Q_NULLPTR));
        label0501->setText(QApplication::translate("MainWindow", "Exposure Mode", Q_NULLPTR));
        label0502->setText(QApplication::translate("MainWindow", "Trigger Selector", Q_NULLPTR));
        label0503->setText(QApplication::translate("MainWindow", "Trigger Mode", Q_NULLPTR));
        label0504->setText(QApplication::translate("MainWindow", "Trigger Source", Q_NULLPTR));
        label0505->setText(QApplication::translate("MainWindow", "Trigger Delay", Q_NULLPTR));
        label0506->setText(QApplication::translate("MainWindow", "Trigger Overlap", Q_NULLPTR));
        label0507->setText(QApplication::translate("MainWindow", "Trigger Software", Q_NULLPTR));
        label0511->setText(QApplication::translate("MainWindow", "Sensor Shutter Mode", Q_NULLPTR));
        label0508->setText(QApplication::translate("MainWindow", "Noise Reduction", Q_NULLPTR));
        label0509->setText(QApplication::translate("MainWindow", "Wait HD", Q_NULLPTR));
        label0510->setText(QApplication::translate("MainWindow", "Wait Read Out", Q_NULLPTR));
        tmFrameStart->setText(QApplication::translate("MainWindow", "Frame Start", Q_NULLPTR));
        tmExposureStart->setText(QApplication::translate("MainWindow", "Exposure Start", Q_NULLPTR));
        tmExposureEnd->setText(QApplication::translate("MainWindow", "Exposure End", Q_NULLPTR));
        tmReadOut->setText(QApplication::translate("MainWindow", "Read Out", Q_NULLPTR));
        tmAutoExposureEndCheck->setText(QApplication::translate("MainWindow", "Auto ExposureEnd Trigger", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(TriggerMode), QApplication::translate("MainWindow", "TriggerMode", Q_NULLPTR));
        label0601->setText(QApplication::translate("MainWindow", "Strobe Start Delay", Q_NULLPTR));
        label0602->setText(QApplication::translate("MainWindow", "Strobe End Delay", Q_NULLPTR));
        label0603->setText(QApplication::translate("MainWindow", "Output Pulse Delay", Q_NULLPTR));
        label0604->setText(QApplication::translate("MainWindow", "Output Pulse Duration", Q_NULLPTR));
        label0605->setText(QApplication::translate("MainWindow", "Read Out Delay", Q_NULLPTR));
        label0606->setText(QApplication::translate("MainWindow", "Line Debounce Time", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(TriggerTiming), QApplication::translate("MainWindow", "TriggerTiming", Q_NULLPTR));
        label0701->setText(QApplication::translate("MainWindow", "IO0", Q_NULLPTR));
        label0702->setText(QApplication::translate("MainWindow", "IO1", Q_NULLPTR));
        label0703->setText(QApplication::translate("MainWindow", "IO2", Q_NULLPTR));
        label0709->setText(QApplication::translate("MainWindow", "Reset Switch", Q_NULLPTR));
        label0705->setText(QApplication::translate("MainWindow", "IN/OUT", Q_NULLPTR));
        label0706->setText(QApplication::translate("MainWindow", "MODE", Q_NULLPTR));
        label0707->setText(QApplication::translate("MainWindow", "NEGA/POSI", Q_NULLPTR));
        label0708->setText(QApplication::translate("MainWindow", "STATUS", Q_NULLPTR));
        label0704->setText(QApplication::translate("MainWindow", "IO3", Q_NULLPTR));
        label0710->setText(QApplication::translate("MainWindow", "SW", Q_NULLPTR));
        label0711->setText(QApplication::translate("MainWindow", "LED", Q_NULLPTR));
        label0714->setText(QApplication::translate("MainWindow", "Temperature", Q_NULLPTR));
        ioResetCounter->setText(QApplication::translate("MainWindow", "reset counter", Q_NULLPTR));
        ioClearBuffer->setText(QApplication::translate("MainWindow", "clear buffer", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(IO), QApplication::translate("MainWindow", "IO", Q_NULLPTR));
        label0801->setText(QApplication::translate("MainWindow", "HDR Mode", Q_NULLPTR));
        label0802->setText(QApplication::translate("MainWindow", "HDR Slope Num", Q_NULLPTR));
        label0803->setText(QApplication::translate("MainWindow", "Knee1", Q_NULLPTR));
        label0804->setText(QApplication::translate("MainWindow", "Vlow2", Q_NULLPTR));
        label0805->setText(QApplication::translate("MainWindow", "Knee2", Q_NULLPTR));
        label0806->setText(QApplication::translate("MainWindow", "Vlow3", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(HDR), QApplication::translate("MainWindow", "HDR", Q_NULLPTR));
        eepLoadStandard->setText(QApplication::translate("MainWindow", "Load[Standard]", Q_NULLPTR));
        eepSaveStandard->setText(QApplication::translate("MainWindow", "Save[Standard]", Q_NULLPTR));
        eepReset->setText(QApplication::translate("MainWindow", "Reset Factory Default", Q_NULLPTR));
        eepLoadDpp->setText(QApplication::translate("MainWindow", "Load[DefectPixelPosition]", Q_NULLPTR));
        eepSaveDpp->setText(QApplication::translate("MainWindow", "Save[DefectPixelPosition]", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(EEPROM), QApplication::translate("MainWindow", "EEPROM", Q_NULLPTR));
        label1001->setText(QApplication::translate("MainWindow", "Scan Mode", Q_NULLPTR));
        label1002->setText(QApplication::translate("MainWindow", "H Decimation Binning", Q_NULLPTR));
        label1004->setText(QApplication::translate("MainWindow", "H/V Binning Sum", Q_NULLPTR));
        label1005->setText(QApplication::translate("MainWindow", "Region", Q_NULLPTR));
        label1007->setText(QApplication::translate("MainWindow", "Offset X", Q_NULLPTR));
        label1008->setText(QApplication::translate("MainWindow", "Offset Y", Q_NULLPTR));
        label1009->setText(QApplication::translate("MainWindow", "Width", Q_NULLPTR));
        label1010->setText(QApplication::translate("MainWindow", "Height", Q_NULLPTR));
        label1012->setText(QApplication::translate("MainWindow", "Clock", Q_NULLPTR));
        label1011->setText(QApplication::translate("MainWindow", "V Blank for FPS", Q_NULLPTR));
        label1013->setText(QApplication::translate("MainWindow", "Transfer bits", Q_NULLPTR));
        label1014->setText(QApplication::translate("MainWindow", "Display Pixel Format", Q_NULLPTR));
        label1015->setText(QApplication::translate("MainWindow", "Color Interpolation", Q_NULLPTR));
        label1016->setText(QApplication::translate("MainWindow", "Mirror Mode", Q_NULLPTR));
        label1017->setText(QApplication::translate("MainWindow", "Rotation Mode", Q_NULLPTR));
        label1006->setText(QApplication::translate("MainWindow", "Region Mode", Q_NULLPTR));
        label1003->setText(QApplication::translate("MainWindow", "V Decimation Binning", Q_NULLPTR));
        label1017_2->setText(QApplication::translate("MainWindow", "FPS", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(Other), QApplication::translate("MainWindow", "Other", Q_NULLPTR));
        label0001->setText(QApplication::translate("MainWindow", "Camera Type", Q_NULLPTR));
        label0002->setText(QApplication::translate("MainWindow", "FPGA Version", Q_NULLPTR));
        label0003->setText(QApplication::translate("MainWindow", "Firm Version", Q_NULLPTR));
        label0004->setText(QApplication::translate("MainWindow", "Driver Version", Q_NULLPTR));
        label0005->setText(QApplication::translate("MainWindow", "Library Version", Q_NULLPTR));
        mainCameraId->setText(QApplication::translate("MainWindow", "Camera ID", Q_NULLPTR));
        mainSettingFile->setText(QApplication::translate("MainWindow", "Setting File", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
